### ISSUE TITLE
Is there a way to get download vs extraction times when we run crictl pull?

### ISSUE THREAD

**Issue by saidas3524** [kubernetes-sigs/cri-tools#1009]
#### What would you like to be added:
I want to get the download and extraction times when crictl pull has run. 
#### Why is this needed:
This helps the teams to understand which layer's download/extraction is taking longer and can bring in efficiencies approapriately.

**Comment by haircommander** [comment]
the CRI doesn't currently expose any "progress" or show anything other than "pulling...pulled". the individual CRI implementations may expose more though. CRI-O, for instance, has a metric that shows the time each layer is taking to be pulled. it has high cardinality, but should work well for your case. I am not sure if we expose anything about image extraction time, though I expect most of the time that goes into pulling an image is spent downloading bytes.

**Comment by afbjorklund** [comment]
Seems to have been suggested before, but not implemented:

* https://github.com/kubernetes-sigs/cri-tools/issues/413

Dating back for quite some time, and was once KEP-1338:

* https://github.com/kubernetes/kubernetes/issues/19077

* https://github.com/kubernetes/enhancements/pull/1338

**Comment by afbjorklund** [comment]
For docker it is dumped in the cri-docker.service logs, but only occasionally (every 10 seconds):

```
level=info msg="Pulling image python: 8f7d05258955: Downloading [==========>                                        ]  40.92MB/196.8MB"
level=info msg="Pulling image python: 8f7d05258955: Downloading [===============================>                   ]  122.2MB/196.8MB"
level=info msg="Stop pulling image python: Status: Downloaded newer image for python:latest"
```

**Comment by afbjorklund** [comment]
There doesn't seem to be any progress update from cri-containerd

**Comment by afbjorklund** [comment]
It should be possible for the CR to provide metrics "afterwards", even if not being able to show progress "during"

All of the KEP so far seem to be focused on the progress bars, which are similar but not identical to the metrics

**Comment by afbjorklund** [comment]
Maybe both are needed ? Or it could be an extension of the existing ones

Would be interesting to have this in place, when the new storage arrives...
