### ISSUE TITLE
Is there a way to run containers with gpus?

### ISSUE THREAD

**Issue by Nomiby** [kubernetes-sigs/cri-tools#1025]
#### What would you like to be added:
I have gone through the proto file and not seeing any existing way for me to use gpus like docker. Want to have a way to specify gpus to use for running containers. Please let me know if there is a way that I am not aware of.

#### Why is this needed:
It's pretty useful to have a gpu support.

Thanks

**Comment by haircommander** [comment]
I think this is what CDI is for https://github.com/container-orchestrated-devices/container-device-interface
They can be passed to CRI implementations through annotations on the container

**Comment by Nomiby** [comment]
> I think this is what CDI is for https://github.com/container-orchestrated-devices/container-device-interface They can be passed to CRI implementations through annotations on the container

Thanks for sharing this. It seems like I need to put some extra configs here to use gpus. Let me take a look. Thanks.
