### ISSUE TITLE
Permission Denied when excute crictl command

### ISSUE THREAD

**Issue by michealliang123** [kubernetes-sigs/cri-tools#1049]
#### What happened:
I just upgrade my EKS cluster to 1.24,and i try to managed my container use crictl,but when i excute "crictl ps" got this error
DEBU[0000] get runtime connection
FATA[0000] unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: permission denied"

#### What you expected to happen:
Normal operation
#### How to reproduce it (as minimally and precisely as possible):
use this command to install
VERSION="v1.24.1"
wget https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-$VERSION-linux-amd64.tar.gz
sudo tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/local/bin
rm -f crictl-$VERSION-linux-amd64.tar.gz
#### Environment:
containerd://1.6.6
5.4.219-126.411.amzn2.x86_64

- Container runtime or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by michealliang123** [comment]
i cant excute docker anymore , and "ctr task ls" shows nothing.
But my pos is in running states
[ec2-user@ip-172-31-21-202 ~]$ kubectl get pod -A
NAMESPACE     NAME                                            READY   STATUS    RESTARTS   AGE
kube-system   aws-load-balancer-controller-68bb746c46-q645h   1/1     Running   0          57m
kube-system   aws-load-balancer-controller-68bb746c46-zkp6m   1/1     Running   0          49m
kube-system   aws-node-cd9kj                                  1/1     Running   0          61m
kube-system   aws-node-g8d72                                  1/1     Running   0          63m
kube-system   aws-node-nf9g5                                  1/1     Running   0          63m
kube-system   aws-node-zldjm                                  1/1     Running   0          65m
kube-system   coredns-58fb67c4db-ll9vp                        1/1     Running   0          57m
kube-system   coredns-58fb67c4db-v5888                        1/1     Running   0          52m
kube-system   kube-proxy-4pm76                                1/1     Running   0          63m
kube-system   kube-proxy-99rgm                                1/1     Running   0          63m
kube-system   kube-proxy-fzbz7                                1/1     Running   0          65m
kube-system   kube-proxy-wv7h6                                1/1     Running   0          61m

**Comment by saschagrunert** [comment]
@michealliang123 thank you for the bug report! Are you running `crictl` as `root` user on the system?

**Comment by afbjorklund** [comment]
Maybe it needs to be documented, that you need to run `crictl` as root if your container runtime requires it ?
