### ISSUE TITLE
PRISMA-2022-0227 - github.com/emicklei/go-restful needs updated to 3.10.1

### ISSUE THREAD

**Issue by KevinPoole** [kubernetes-sigs/cri-tools#1050]
Hi all,

Twistlock scans currently flag crictl v1.26.0 with the above mentioned vulnerability "PRISMA-2022-0227".

More information can be found here: https://github.com/emicklei/go-restful/issues/497

It seems the fix is to just bump github.com/emicklei/go-restful up to at least 3.10.1.

-Kevin

**Comment by saschagrunert** [comment]
Looks like we use go-restful via `k8s.io/kube-openapi`: https://github.com/kubernetes/kube-openapi/blob/10e5f0effbd23ac351f8da2138292759505a93a8/go.mod#L8

**Comment by justdan96** [comment]
@saschagrunert it's here in the go.mod: https://github.com/kubernetes-sigs/cri-tools/blob/master/go.mod#L44
