### ISSUE TITLE
Release 1.26.0 Checksum's don't match

### ISSUE THREAD

**Issue by bandwiches** [kubernetes-sigs/cri-tools#1051]
#### What happened:
Not sure if this is really an error, but the release package 1.26.0 checksum does not match the provided 256/512 checksum files.  It does match the written checksum in the release description.

#### What you expected to happen:
Expected the 256/512 checksums to match the package checksum.

#### How to reproduce it (as minimally and precisely as possible):

1. Download `crictl-v1.26.0-linux-amd64.tar.gz`
2. Download `crictl-v1.26.0-linux-amd64.tar.gz.sha256`
3. Download `crictl-v1.26.0-linux-amd64.tar.gz.sha512`

Compare sha256sum and sha512sum between the related files.

#### Anything else we need to know?:
The checksum of the package matches the checksum in the release description, but not the associated 256/512 checksum files in the same release.

#### Environment:
N/A

**Comment by saschagrunert** [comment]
@bandwiches thank you for the report! The file `crictl-v1.26.0-linux-amd64.tar.gz.sha512` just contains the checksum for `crictl-v1.26.0-linux-amd64.tar.gz`, which indeed matches:

```
> sha512sum crictl-v1.26.0-linux-amd64.tar.gz
a3a2c02a90b008686c20babaf272e703924db2a3e2a0d4e2a7c81d994cbc68c47458a4a354ecc243af095b390815c7f203348b9749351ae817bd52a522300449  crictl-v1.26.0-linux-amd64.tar.gz
> cat crictl-v1.26.0-linux-amd64.tar.gz.sha512
a3a2c02a90b008686c20babaf272e703924db2a3e2a0d4e2a7c81d994cbc68c47458a4a354ecc243af095b390815c7f203348b9749351ae817bd52a522300449
```

You're right, the SHA's of the files itself differ, but that's totally intentional :slightly_smiling_face:

**Comment by bandwiches** [comment]
I am a fool.  Thanks! :)
