### ISSUE TITLE
crictl 1.19.0 and cri-o >= 1.26 as runtime result in unknown service runtime.v1alpha2

### ISSUE THREAD

**Issue by chg-dio** [kubernetes-sigs/cri-tools#1069]
#### What happened:
crictl isn't working with cri-o >= 1.26 anymore

#### What you expected to happen:
crictl can control cri-o in v1.26

#### How to reproduce it (as minimally and precisely as possible):
See details here: https://github.com/cri-o/cri-o/issues/6554

#### Environment:

See details here: https://github.com/cri-o/cri-o/issues/6554

**Comment by haircommander** [comment]
what version of crictl? It may need to be upgraded to 1.26.0

**Comment by chg-dio** [comment]
Sorry! crictl 1.19.0 - as mentioned in https://github.com/cri-o/cri-o/issues/6554

**Comment by haircommander** [comment]
1.19 is quite out of date. I think the versions of crictl that are supported are only 1.24 and later, would you try one of those?

**Comment by chg-dio** [comment]
Ok, that seems to be a OS topic.
It is working with crictl 1.26 but the default crictl installed is v1.19 and my binary is ignored.

Sorry to bother you!
