### ISSUE TITLE
Makefile: pass in a custom variable GOARCH 

### ISSUE THREAD

**Issue by dongsupark** [kubernetes-sigs/cri-tools#1072]
#### Why is this needed:

While working on a new version of cri-tools in [Flatcar Container Linux](https://github.com/flatcar/coreos-overlay/pull/2415), I realized it was not possible to pass in `${GOARCH}` to Makefile of cri-tools. As a result, ebuilds of Gentoo-derivatives cannot make use of simple commands like `emake`, but have to explicitly run `go build` or its wrappers.

That's probably one of the reasons why cri-tools of Gentoo still does not support [arm64](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-containers/cri-tools/cri-tools-1.25.0.ebuild).

It should be possible to pass in `${GOARCH}` to Makefile, like `${GOOS}` or other env variables.

**Comment by haircommander** [comment]
This makes sense, do you have any desire to open a PR @dongsupark ?

**Comment by dongsupark** [comment]
@haircommander 
Filed a PR https://github.com/kubernetes-sigs/cri-tools/pull/1074.
