### ISSUE TITLE
crictl runtime connetion error

### ISSUE THREAD

**Issue by smhakcan** [kubernetes-sigs/cri-tools#1073]
DEBU[0000] get runtime connection
FATA[0000] validate service connection: CRI v1 runtime API is not implemented for endpoint "unix:///run/containerd/containerd.sock": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService

I use as runtime containerd

**Comment by saschagrunert** [comment]
@smhakcan did you configure containerd to use CRI v1?

**Comment by afbjorklund** [comment]
This error is expected, if trying to use containerd 1.5 with newer cri-tools (such as 1.26.0)

**Comment by SergeyKanzhelev** [comment]
/close

since it is an expected error
