### ISSUE TITLE
Return an empty LogPath from crictl inspect

### ISSUE THREAD

**Issue by LinTechSo** [kubernetes-sigs/cri-tools#1078]
Hi all.

My problem is that, after i execute below command for getting container inspect information, the Log Path field in JSON output is None and i don't know why

would you please help me figure this out.

```
./crictl --runtime-endpoint /host/run/dockershim.sock inspect --output=json [container_ID] | jq
```

```
{
  "status": {
    "id": "70efc011fcb7d881eb036a865569eebe8bc24c182d6225279054f96f44",
      ........
    "mounts": [],
    "logPath": "",
    "resources": null
  }
}
```

**Comment by haircommander** [comment]
what version of crictl and what CRI server are you using?

**Comment by LinTechSo** [comment]
crictl version v1.25.0
Docker



some nodes are cri-o and some docker 
but i see empty log path on Docker node

**Comment by haircommander** [comment]
is it the mirantis cri-dockerd ? I don't know if anyone here is very familiar with it, it may be worth opening an issue in their repo

**Comment by LinTechSo** [comment]
I'am using dockershim as runtime endpoint crictl

**Comment by haircommander** [comment]
hm, the dockershim support was dropped in 1.24, so I think either you need to move to cri-dockerd, or totally to cri-o (as a cri-o dev, my preference is the latter :smile: )

**Comment by LinTechSo** [comment]
Hi. 
I have an update about this issue.

The log of my container actually exists in `/host/var/lib/docker/containers` and the problem comes from crictl i think

**Comment by haircommander** [comment]
it's up to the cri server to populate that information. crictl just relays what it gets from the [container status call](https://github.com/kubernetes-sigs/cri-tools/blob/47f9d2759546fb4be7bc69d01620ce8fd0219591/cmd/crictl/container.go#L896)

**Comment by SergeyKanzhelev** [comment]
/close

This sounds like the dockershim issue that is not supported any longer. Just checked on containerd - `logPath` is populated correctly
