### ISSUE TITLE
getRuntimeService can't get the right sock

### ISSUE THREAD

**Issue by helen-frank** [kubernetes-sigs/cri-tools#1089]
#### What happened:

```shell
./crictl ps
WARN[0000] runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead.
WARN[0000] image connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead.
E0209 07:33:47.702320  159566 remote_runtime.go:390] "ListContainers with filter from runtime service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/dockershim.sock: connect: no such file or directory\"" filter="&ContainerFilter{Id:,State:&ContainerStateValue{State:CONTAINER_RUNNING,},PodSandboxId:,LabelSelector:map[string]string{},}"
FATA[0000] listing containers: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/dockershim.sock: connect: no such file or directory"
```
#### What you expected to happen:

```shell
./crictl -r unix:///run/containerd/containerd.sock ps
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID              POD
```
#### How to reproduce it (as minimally and precisely as possible):

```shell
apt install docker

cat /etc/containerd/config.toml
disabled_plugins = [""]

systemctl restart containerd

./crictl ps
```
#### Anything else we need to know?:

kubelet/ri/remote/remote_runtime.go func validateServiceConnection() err check bug will cause getRuntimeService to fail to select sock correctly

https://github.com/kubernetes-sigs/cri-tools/blob/09537079cf85593804adb0c1709fe5ba1778b6fa/vendor/k8s.io/kubernetes/pkg/kubelet/cri/remote/remote_image.go#L92

It was resolved in the kubernetes

https://github.com/kubernetes/kubernetes/blob/119dc95369150964d76149208ff6d0f0542798bf/pkg/kubelet/cri/remote/remote_image.go#L90

#### Environment:

- Container runtime or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04.1 LTS
- Kernel (e.g. `uname -a`):5.15.0-60-generic
- Others:

**Comment by saschagrunert** [comment]
Hey @helen-frank, thank you for submitting the issue. What is the content of `/etc/crictl.yaml`? I assume you have containerd and docker running on the local system so crictl will use docker.

**Comment by helen-frank** [comment]
Yes, I installed docker first and used the crictl plugins by modifying the containerd's /etc/containerd/config.toml, so I found that crictl cannot be used by default endpoints without setting the image-endpoint.

**Comment by helen-frank** [comment]
I am currently studying cri and containerd. I hope they will become stronger and easier to use.😀

**Comment by saschagrunert** [comment]
@helen-frank you can set the values in `/etc/crictl.yaml`, like:

```yaml
runtime-endpoint: "unix:///var/run/crio/crio.sock"
timeout: 0
debug: false
```

**Comment by helen-frank** [comment]
Yes, I kown. My idea is to raise this problem and hope to solve this problem by upgrading dependency as soon as possible.

**Comment by allidoiswin10** [comment]
Hi, out of curiosity what version of cri-tools and containerd are you using?

**Comment by helen-frank** [comment]
> Hi, out of curiosity what version of cri-tools and containerd are you using?

The crictl compiled by the master branch, I mean, the code dependency needs to be updated. You can compare the code in the link I gave above.

**Comment by afbjorklund** [comment]
Seems to be the same issue as:
* https://github.com/kubernetes-sigs/cri-tools/issues/1041

No idea why dockershim is still in the list, since it doesn't even work anymore (with v1)
Or why containerd has been moved _before_ docker, but then again it has CRI disabled.

**Comment by gandush** [comment]
Just create /etc/crictl.yaml and add follow lines

runtime-endpoint: "unix:///var/run/containerd/containerd.sock"
image-endpoint: ""
timeout: 0
debug: false
pull-image-on-create: false
disable-pull-on-run: false

Everything works fine.

**Comment by babu97** [comment]
Assuming you have master  and worker nodes must you set containerd   create /etc/crictl.yaml on all the nodes?
