### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/cri-tools#1100]
@kubernetes-sigs/cri-tools-admins @kubernetes-sigs/cri-tools-maintainers are you happy with renaming `master` to `main` in this repository?

**Comment by feiskyer** [comment]
I think it should be ok, but are there any concerns keeping the old branch name? It seems the branch name in other projects are not renamed yet.

**Comment by saschagrunert** [comment]
Closing for now, considering that we have no agreement reached yet.
