### ISSUE TITLE
crictl exec failed connection using 127.0.0.1 in IPv6-only Kubernetes

### ISSUE THREAD

**Issue by password636** [kubernetes-sigs/cri-tools#1126]
#### What happened:
I'm running a crictl command in a IPv6-only K8s Cluster and get this error
```
bash-5.0# crictl -debug -r unix:///host/container-runtime.sock exec 4b3f4647627f37cf62bba7b7c305da087e87d0f5b8c85c81e9ecd43fcf0406d5 ls
DEBU[0000] get runtime connection
DEBU[0000] connect using endpoint 'unix:///host/container-runtime.sock' with '2s' timeout
DEBU[0000] connected successfully using endpoint: unix:///host/container-runtime.sock
DEBU[0000] ExecRequest: &ExecRequest{ContainerId:4b3f4647627f37cf62bba7b7c305da087e87d0f5b8c85c81e9ecd43fcf0406d5,Cmd:[ls],Tty:false,Stdin:false,Stdout:true,Stderr:true,}
DEBU[0000] ExecResponse: &ExecResponse{Url:http://127.0.0.1:34955/exec/gU1PMC4l,}
DEBU[0000] Exec URL: http://127.0.0.1:34955/exec/gU1PMC4l
DEBU[0000] StreamOptions: {<nil> 0xc00000e018 0xc00000e020 false <nil>}
FATA[0000] execing command in container: error sending request: Post "http://127.0.0.1:34955/exec/gU1PMC4l": dial tcp 127.0.0.1:34955: connect: connection refused
```
The command is executed inside a container. It is to execute some command (`ls` in this case) in another container with container ID `4b3f4647627f37cf62bba7b7c305da087e87d0f5b8c85c81e9ecd43fcf0406d5` on the same node. The container runtime is `containerd`.

Is this error because crictl exec is using `127.0.0.1` instead of `::1` ? How can I let crictl use `::1`?

#### What you expected to happen:
The `crictl exec` command can succeed.
#### How to reproduce it (as minimally and precisely as possible):
In an IPv6-only Kubernetes, execute the command in a Container for another Container on the same node.
#### Environment:

- Container runtime or hardware configuration: containerd
- OS (e.g: `cat /etc/os-release`): alpine linux
- Kernel (e.g. `uname -a`):  SMP Debian 5.10.162-1 (2023-01-21) x86_64 Linux
- Others:
This is the `/etc/hosts` file viewed inside the container, not sure it matters. 
```
bash-5.0# cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
```

**Comment by saschagrunert** [comment]
Looks like the host is defined there and not configurable right now: 

https://github.com/kubernetes-sigs/cri-tools/blob/4daea44918cc34b63617c6c9e9923f43d47ddfdd/cmd/crictl/exec.go#L39

**Comment by bitoku** [comment]
You may want to set `StreamServerAddress` in config.toml.

It seems containerd respects that config and returns that address to cri client.

https://github.com/containerd/containerd/blob/main/docs/cri/config.md#full-configuration
