### ISSUE TITLE
cri-tools 1.26.0 pull image error

### ISSUE THREAD

**Issue by yanhuan0802** [kubernetes-sigs/cri-tools#1137]
#### What happened:

When I run the command **crictl pull victoriametrics/victoria-metrics:v1.76.1** to pull the image, I get the error PullImage from image service failed

In fact, I tried pulling several container images and they all showed similar errors, such as cnych/prometheus-adapter:v0.10.0, bitnami/kube-state-metrics:v2.8.2, grafana/grafana:8.5.22 and so on. However, some container images can be successfully pulled, such as docker.io/grafana/grafana:latest, quay.io/prometheus-operator/prometheus-operator:v0.64.0, docker.io/library/ redis, etc.

#### What you expected to happen:

crictl pull victoriametrics/victoria-metrics:v1.76.1
E0417 01:47:55.256339   59141 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"docker.io/victoriametrics/victoria-metrics:v1.76.1\": failed to unpack image on snapshotter overlayfs: unexpected media type text/html for sha256:04a732b9876d77c18601b92f91bb05d4591a1356dbbfd732c13f4db1362c796d: not found" image="victoriametrics/victoria-metrics:v1.76.1"
FATA[0002] pulling image: rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/victoriametrics/victoria-metrics:v1.76.1": failed to unpack image on snapshotter overlayfs: unexpected media type text/html for sha256:04a732b9876d77c18601b92f91bb05d4591a1356dbbfd732c13f4db1362c796d: not found

#### How to reproduce it (as minimally and precisely as possible):
install kubernetes 1.26.4 and containerd 1.6.20, pull the above container image with the error.

#### Anything else we need to know?:
When I use crictl version v1.22.0 to pull the above image, it works.

#### Environment:

- Container runtime or hardware configuration:
    - kubernetes 1.26.4
    - containerd 1.6.20
- OS (e.g: `cat /etc/os-release`):
    - NAME="Ubuntu"
    - VERSION="20.04.6 LTS (Focal Fossa)"
- Kernel (e.g. `uname -a`):
    - Linux 5.4.0-146-generic 163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by SergeyKanzhelev** [comment]
what version of Containerd are you using with crtictl 1.22.0? Can it be using dockershim instead of containerd?

Without looking any deeper now, here is the link to one of the known issues: https://cloud.google.com/kubernetes-engine/docs/troubleshooting/container-runtime#config-mediatype

**Comment by yanhuan0802** [comment]
> what version of Containerd are you using with crtictl 1.22.0? Can it be using dockershim instead of containerd?
> 
> Without looking any deeper now, here is the link to one of the known issues: https://cloud.google.com/kubernetes-engine/docs/troubleshooting/container-runtime#config-mediatype

When I use crictl 1.22.0, the corresponding containerd version is containerd v1.6.0.
```
crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.6.0
RuntimeApiVersion:  v1alpha2
```

**Comment by kwilczynski** [comment]
@yanhuan0802, are you still having issues with image pulls?

The error you included per:

```
E0417 01:47:55.256339 59141 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/victoriametrics/victoria-metrics:v1.76.1": failed to unpack image on snapshotter overlayfs: unexpected media type text/html for sha256:04a732b9876d77c18601b92f91bb05d4591a1356dbbfd732c13f4db1362c796d: not found"
```

Especially the `text/html` MIME type would be an indication that either the Docker registry or some intermediate proxy is currently having an issue and might be returning an error page.

This normally would be transient.

**Comment by yanhuan0802** [comment]
> @yanhuan0802, are you still having issues with image pulls?
> 
> The error you included per:
> 
> ```
> E0417 01:47:55.256339 59141 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/victoriametrics/victoria-metrics:v1.76.1": failed to unpack image on snapshotter overlayfs: unexpected media type text/html for sha256:04a732b9876d77c18601b92f91bb05d4591a1356dbbfd732c13f4db1362c796d: not found"
> ```
> 
> Especially the `text/html` MIME type would be an indication that either the Docker registry or some intermediate proxy is currently having an issue and might be returning an error page.
> 
> This normally would be transient.

Thank you very much. I'll try again.
