### ISSUE TITLE
'crictl rm(p) -af' display help when there is nothing to delete

### ISSUE THREAD

**Issue by champtar** [kubernetes-sigs/cri-tools#1144]
#### What happened:
Using
```
crictl rmp -af
crictl rm -af
```
display the help menu when there are no containers/pods left to delete

#### What you expected to happen:
either display nothing or a message saying that there is nothing to delete

#### How to reproduce it (as minimally and precisely as possible):
run `crictl rm -af` twice

#### Environment:

- Container runtime or hardware configuration: containerd 1.7.0 / crictl 1.26.0

**Comment by saschagrunert** [comment]
@champtar good point, do you mind opening a PR to fix that behavior?

**Comment by champtar** [comment]
@saschagrunert #1147
