### ISSUE TITLE
Update Containerd in CI matrix to latest 1.6

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes-sigs/cri-tools#1154]
Follow up from https://github.com/kubernetes-sigs/cri-tools/pull/1146#issuecomment-1533490120

Should we just use 1.6 to use latest of 1.6 for tests? I don't have context here and wonder what is the reasoning behind 1.6.2. Does CI test with oldest or newest?

cc @mikebrow

**Comment by mikebrow** [comment]
1.6.x being an LTS service release with sufficient extra CRI functionality backported/cherry picked as we go along, 
we should be testing with a matrix of 1.6, 1.7.x and main

Of course every PR is tested against a version of critest but we may fall behind in specifying updated versions of cri-tools

**Comment by mikebrow** [comment]
the only exception to 
version: [main, v1.6.x, v1.7.x]

would be when there is an issue cri-tools or containerd being on the wrong with a CRI api version or other needed change in kubelet vendor which happens sometimes..

**Comment by mikebrow** [comment]
https://github.com/containerd/containerd/pull/8474 moving containerd main up to latest cri-tools

**Comment by afbjorklund** [comment]
Something similar to this: https://containerd.io/releases/#kubernetes-support
