### ISSUE TITLE
Correct way to delete pod

### ISSUE THREAD

**Issue by anupamdialpad** [kubernetes-sigs/cri-tools#1166]
#### What happened:
To delete a pod I am using the following command
```bash
podID=`crictl pods --label app=random -q`
crictl stopp $podID
crictl rmp $podID 
```
But this errors out with 
```
container is already in removing state
```
#### What you expected to happen:
The commands seems reasonable to delete a particular pod. I want to know the correct way to delete pod using crictl

#### Environment:

- Container runtime or hardware configuration: containerd version 1.6.21
- OS (e.g: `cat /etc/os-release`):  Debian GNU/Linux 11 (bullseye)
- Kernel (e.g. `uname -a`): 5.10.0
- Crictl version: 1.25.0
- kubernetes version 1.25.9

**Comment by anupamdialpad** [comment]
Sorry for the late response.
I copied the commands in a bash script and ran it again but it did not work.
This is the bash script
```bash
crictl pods
crictl ps
podID=`crictl pods --label k8s-app=cilium -q`
crictl stopp $podID
crictl rmp $podID
```

This is the output
```
POD ID              CREATED             STATE               NAME                NAMESPACE           ATTEMPT             RUNTIME
18f246206374b       2 hours ago         Ready               cilium-5rr6p        kube-system         0                   (default)
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID
61d0c37fc5cff       ee632ef66ce15       2 hours ago         Running             cilium-agent        0                   18f246206374b
Stopped sandbox 18f246206374b349661535d367f6f323204d58ffec0c51e455729ed26cd4f7ef
removing the pod sandbox "18f246206374b349661535d367f6f323204d58ffec0c51e455729ed26cd4f7ef": rpc error: code = Unknown desc = failed to remove container "a2b2aa8ff31d9e1667662590b6f5ba6ef1c888ca6012767e932fada54f3e5a78": failed to set removing state for container "a2b2aa8ff31d9e1667662590b6f5ba6ef1c888ca6012767e932fada54f3e5a78": container is already in removing state
```

**Comment by kundan2707** [comment]
@anupamdialpad  there is a bug still open in containerd repo.
https://github.com/containerd/containerd/issues/6565 
There are few ways given to fix it but not resolved completely yet

**Comment by anupamdialpad** [comment]
Okay, this can be closed then.
