### ISSUE TITLE
Update  k8s.io/kubernetes to v1.27.2

### ISSUE THREAD

**Issue by tshaiman** [kubernetes-sigs/cri-tools#1203]
#### What happened:
we got flagged by a Security Vulnerability issue effected by go-lang k8s.io/kubernetes package
https://github.com/advisories/GHSA-xc8m-28vv-4pjc

#### What you expected to happen:
update the k8s.io/kubernetes package to v1.27.2

#### How to reproduce it (as minimally and precisely as possible):
https://github.com/advisories/GHSA-xc8m-28vv-4pjc

#### Environment:
Prod

- Container runtime or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by saschagrunert** [comment]
@tshaiman thank you for the report! We're not using the seccomp code paths here in cri-tools:

```
> ls vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime
logs/
```

Files using the code are:
- pkg/kubelet/kuberuntime/helpers_linux_test.go
- pkg/kubelet/kuberuntime/security_context.go
- pkg/kubelet/kuberuntime/helpers.go

**Comment by tshaiman** [comment]
still our scanner finds that the k8s.io/kubernetes in the crictl needs to upgraded to 1.27.2. the vulnerability is with the lib reference regarding if you use it or not

**Comment by saschagrunert** [comment]
@tshaiman crictl is right now on v1.27.0 and the next logical version would be v1.27.1. We plan to release a new version together with v1.28, which would around Aug 15. Would that work for you?

**Comment by tshaiman** [comment]
@saschagrunert  actually this timeline is a bit problematic for us, as the vulnerability marked as "medium/important" 
can you move directly to 1.27.2 ?

**Comment by saschagrunert** [comment]
Hm, we need to plan for that since I have to cut a new release including all the packaging updates.

**Comment by saschagrunert** [comment]
Done in https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.27.1
