### ISSUE TITLE
Feature: crictl login

### ISSUE THREAD

**Issue by xogoodnow** [kubernetes-sigs/cri-tools#1204]
#### What would you like to be added:
Add login functionality to crictl  (crictl login)

#### Why is this needed:
Almost all registries (including but not limited to docker.io) have rate limit on non-authenticated users. So the rate limit would be reached almost immediately in large clusters which are using Crio as runtime.
Currently, using "Podman auth" or "--cerds" are work around methods which are unacceptable for a project at this scale (so much manual labor). Also since manual intervention is required at every step, automation mechanisms for resource utilization would become useless on Production env.

**Comment by xogoodnow** [comment]
If you accept this issue, I would like to work on it.

**Comment by saschagrunert** [comment]
Hey @xogoodnow thank you for the request!

Hm, having a crictl login would only store the credentials locally, right? Or do you plan to lookup existing auth files/directories like `containers/auth.json`?

**Comment by xogoodnow** [comment]
Hi @saschagrunert,

I believe using the "containers/auth.json" method would be the most efficient, by default "crictl login" command would login to dockehub and retrieve the token which would be stored in "containers/auth.json".
In my opinion the following switches are also needed:
crictl login --repo (to specify the custom repo address)
crictl logout (to log out from all repos)
crictl logout --repo (log out from specific repo)
crictl login --user-name <USERNAME> --password <PASSWORD>


I would be more than happy to add the aforementioned functionalities.

**Comment by saschagrunert** [comment]
But we also need to support other runtimes than CRI-O, for example containerd. We would also write to those files, means that we probably import libraries to simplify that. I'm not exactly sure about that feature, since it depends on the used underlying runtime.

@kubernetes-sigs/cri-tools-maintainers what are your thoughts on that?

**Comment by xogoodnow** [comment]
You are right but keep in mind that Containerd can handle this by editing "plugins."io.containerd.grpc.v1.cri".registry.configs" once. This way the user would be able to increase the rate limit but on Crio there is no automated way to do this, I had to change my Operator so it would specify my credentials  every time it needed to pull an image with crictl. Instead of this which is very bad practice (in my opinion) it would be wonderful if I could just login to my repo and use the token.

**Comment by SergeyKanzhelev** [comment]
The good thing about crictl today is that it's behavior in terms of image downloads is close to what we see in k8s-to-cri interaction. So we can use crictl to troubleshoot issues. If crictl "login" will be used to configure runtimes, it preserve this nice property of the tool. If there will be separate credentials, it will change the expectation of the tool.

**Comment by xogoodnow** [comment]
Hi @SergeyKanzhelev,
how to you think I could handle this problem (rate limit)
I am hosting a k8s as a service platform, there are 100s of pods being created on my workers every hour, since I use a SNI to download the images I am reaching the rate limit all the time. Currently I am using an IP pool for my SNI to bypass this issue but I believe a login mechanism (the concept) is required for Crictl.
How can we automate this process (not using --cerd each time)?

**Comment by xogoodnow** [comment]
Hi, are there any updates on this matter?
We are using Cri-o on our production environment and we would appreciate it if you could give us any update about this issue.
