### ISSUE TITLE
Enforce supplying the export option to checkpoint command

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes-sigs/cri-tools#1235]
#### What happened:

Make troubleshooting of this: https://github.com/kubernetes-sigs/cri-tools/issues/1233#issuecomment-1670120523 easier

#### What you expected to happen:

Export argument needs to be required and better documented as a tar file path.

#### How to reproduce it (as minimally and precisely as possible):

See https://github.com/kubernetes-sigs/cri-tools/issues/1233#issuecomment-1670120523 

cc: @adrianreber

/help

**Comment by adrianreber** [comment]
I can look into this.
