### ISSUE TITLE
Debian packages stopped on 1.26?

### ISSUE THREAD

**Issue by thorleifjacobsen** [kubernetes-sigs/cri-tools#1244]
Seems like I cannot find 1.28 of cri-tools on my debian for 1.28 install of kubernetes.

https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/cri-tools

Will that be an issue for my installation?

**Comment by saschagrunert** [comment]
You can try those if you want: https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/

**Comment by afbjorklund** [comment]
It's a bigger problem when you try to use the new cri-tools on the older clusters:

* https://github.com/kubernetes-sigs/cri-tools/issues/1130

So the packages on Kubic and the packages on Google are not updated, on purpose.

**Comment by afbjorklund** [comment]
https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/
