### ISSUE TITLE
cri-tools support matrix is confusing

### ISSUE THREAD

**Issue by haiwu** [kubernetes-sigs/cri-tools#1245]
#### What would you like to be added:
cri-tools support matrix is confusing

In terms of its support matrix, do we need to ensure the same cri-tools version same as k8s version minor release version? 

for example, do we have to install cri-tools 1.27 in order to support k8s 1.27? per tests, it seems cri-tools 1.26 works for k8s 1.25/1.26/1.27 at least. 

#### Why is this needed:
It is not clear for its support matrix. Please clarify. Right now it is not clear at all.

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes-sigs/cri-tools/issues/1153

**Comment by saschagrunert** [comment]
Alright, thank you for the feedback @haiwu, I'm closing this one in favor of https://github.com/kubernetes-sigs/cri-tools/issues/1153
