### ISSUE TITLE
When Containerd default set SystemdCgroup is true, cri-tools test faild

### ISSUE THREAD

**Issue by lengrongfu** [kubernetes-sigs/cri-tools#1292]
#### What happened:
ci: https://github.com/containerd/containerd/actions/runs/6841588084/job/18602143108?pr=9350
When Containerd default set SystemdCgroup is true, the generated cgroupsPath is invalid.

```
Nov 12 15:46:57.970: INFO: Unexpected error occurred: rpc error: code = Unknown desc = failed to start sandbox "31ebf25aed49dcfb889acea7a7dbfdf09b65bb8deeeb4011b9a809f92660bae8": failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: expected cgroupsPath to be of format "slice:prefix:name" for systemd cgroups, got "/k8s.io/31ebf25aed49dcfb889acea7a7dbfdf09b65bb8deeeb4011b9a809f92660bae8" instead: unknown
  [FAILED] in [It] - github.com/kubernetes-sigs/cri-tools/pkg/framework/util.go:217 @ 11/12/23 15:46:57.97
```

#### Environment:

- Container runtime or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by lengrongfu** [comment]
containerd pr: https://github.com/containerd/containerd/pull/9350

**Comment by akhilerm** [comment]
@lengrongfu Can this be of use here https://github.com/kubernetes/kubernetes/pull/118770, getting the cgroup driver from the container runtime itself.
