### ISSUE TITLE
when we transition from SPDY to WebSockets in exec and attach

### ISSUE THREAD

**Issue by duguhaotian** [kubernetes-sigs/cri-tools#1296]
#### What would you like to be added:

K8s have merged pr: https://github.com/kubernetes/kubernetes/pull/119186

KEP: https://github.com/kubernetes/enhancements/issues/4006

#### Why is this needed:
container runtime need to test this new feature

**Comment by saschagrunert** [comment]
@duguhaotian thank you for the request. Do you plan to contribute the feature to cri-tools?

**Comment by duguhaotian** [comment]
> @duguhaotian thank you for the request. Do you plan to contribute the feature to cri-tools?

sorry, i just want to know our plan.
