### ISSUE TITLE
Documentation of pod-config and container-config schema

### ISSUE THREAD

**Issue by ptwales** [kubernetes-sigs/cri-tools#1309]
#### What would you like to be added:

Complete documentation of the schemas for the `pod-config.[yaml|json]` and `container-config.[json|yaml]` used by the `crictl run` and `crictl runp` commands.  _Or links to external documentation if these schemas are defined externally_. 

#### Why is this needed:

Currently only minimal examples are present in [the documentation](https://github.com/kubernetes-sigs/cri-tools/tree/master/docs).  Basic fields such as mounts, environment variables, etc. are not mentioned.

I suspect this is entirely defined externally by CRI but I can't find any documentation at all on [it's website](https://cri-o.io/) nor on k8s.  Does the documentation for any of these files exist outside of go code?

I've chased down [this reference](https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/util.go#L38) to these:
- [ContainerConfig](https://pkg.go.dev/k8s.io/cri-api@v0.28.4/pkg/apis/runtime/v1#ContainerConfig)
- [PodSandboxConfig](https://pkg.go.dev/k8s.io/cri-api@v0.28.4/pkg/apis/runtime/v1#PodSandboxConfig)
I don't even know if this is correct though.

**Comment by saschagrunert** [comment]
@ptwales thank you for reaching out! The schemas are mappings to the CRI api fields: https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto

Maybe we can enhance the docs to mention and link them. Do you want to collaborate on this change?
