### ISSUE TITLE
Documentation: State that crictl is GA since v1.11.0

### ISSUE THREAD

**Issue by jonas27** [kubernetes-sigs/cri-tools#1330]
### What would you like to be added:
Minor fix: State in the docs that crictl is GA (not beta) since version `v1.11.0`, see [release](https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.11.0)

**Comment by afbjorklund** [comment]
Not only that, but `crictl` is now also a hard requirement from `kubeadm` (since v1.24)

**Comment by jonas27** [comment]
@afbjorklund not sure if that should be added as well.

**Comment by afbjorklund** [comment]
It was just context, changing the text to GA is fine.
