### ISSUE TITLE
critest should cover UserNamespace

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes-sigs/cri-tools#1348]
#### What would you like to be added:

CRI API supports `UsernamespaceMode`, but this doesn't seem covered in critest

#### Why is this needed:
For
- https://github.com/kubernetes/enhancements/issues/127

**Comment by AkihiroSuda** [comment]
cc @rata

**Comment by saschagrunert** [comment]
Yeah I guess this was already on the plan for v1.31. Do you want to work on that @AkihiroSuda?

**Comment by rata** [comment]
I fully agree. If any of you can help, it will be great! :)

**Comment by saschagrunert** [comment]
I can, probably from next week. If @AkihiroSuda want to jump in then I'm happy to step back :)

**Comment by saschagrunert** [comment]
Working towards the goal in https://github.com/kubernetes-sigs/cri-tools/pull/1354
