### ISSUE TITLE
With checkpointing being supported in the CRI (at least for CRIO), can we add a checkpoint command to crictl.

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/cri-tools#1349]
#### What would you like to be added:

Add a checkpoint command to crictl so people could checkpoint using this tool.

#### Why is this needed:

Increase visibility in checkpointing

**Comment by kannon92** [comment]
cc @adrianreber

**Comment by adrianreber** [comment]
This already exists: https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/container.go#L612

**Comment by kannon92** [comment]
/close
ah I see.
