### ISSUE TITLE
No help topic for 'restore'

### ISSUE THREAD

**Issue by HFourier** [kubernetes-sigs/cri-tools#1376]
When I want to restore xxx.tar, a checkpoint file that created by k8s, by using command "crictl restore --import=<archive>". I was told No help topic for 'restore'. I want to know how can I restore checkpoint by crictl, this is so important for us.

**Comment by saschagrunert** [comment]
Hey @HFourier, thank you for the report. Do you plan to contribute this documentation enhancement?

**Comment by HFourier** [comment]
> Hey @HFourier, thank you for the report. Do you plan to contribute this documentation enhancement?

I still beginner and I don't think I can help to enhance this documentation.  In addition,  I confuse that I can see  "crictl restore --import=<archive>" is somewhere, but still less information about this. I want to know how can I use this command?

**Comment by saschagrunert** [comment]
Ah the command `restore` does not even exist @HFourier.

**Comment by HFourier** [comment]
> Ah the command `restore` does not even exist @HFourier.

This is wired, I see it in YouTu [https://www.youtube.com/watch?v=0RUDoTi-Lw4](Kubernetes and Checkpoint Restore - Adrian Reber, Red Hat) at timeline16:58.

**Comment by saschagrunert** [comment]
I assume during that time we discussed how the subcommand should look like. You're looking for `crictl checkpoint`, right?

cc @adrianreber

**Comment by adrianreber** [comment]
Exactly. That changed a couple of times. Sometimes I was using PRs in my demos that were not merged.

If you look at https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/ you can see two approaches how to restore checkpoints.

**Comment by HFourier** [comment]
> Exactly. That changed a couple of times. Sometimes I was using PRs in my demos that were not merged.
> 
> If you look at https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/ you can see two approaches how to restore checkpoints.

OK, That would make sense. Thanks for reply!

**Comment by HFourier** [comment]
> Exactly. That changed a couple of times. Sometimes I was using PRs in my demos that were not merged.
> 
> If you look at https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/ you can see two approaches how to restore checkpoints.

May I have another question? I have followed this [url ](https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/). Unfortunately , I meet some trouble.  I try restore the pod from image build by _buildah_ , but it only can succeed in local machine. When I save checkpoint in machine  A and transfer the .tar file to machine B, then try to build images and restore pod in machine B. It failed. And we try to build the image in machine A and push it to docker.io, then restore pod by pulling images at machine B , it has the same problem.   By _kubectl describe pod <name>_, we can get the following information :
` Error: failed to restore container migration: container restore failed: time="2024-03-04T09:23:54+08:00" level=error msg="criu failed: type RESTORE errno 0
log file: /run/containers/storage/overlay-containers/migration/userdata/restore.log" `
We try to find the restore.log, but we can't get this path. When we cd into `/run/containers/storage/overlay-containers`, we can only see some folders such as "483162fff3a8ba5c116bec0c5677118202237326543ff4d661f4c0b1d6866f2f"

**Comment by adrianreber** [comment]
@HFourier Adding comments to tickets which are already closed have a high chance to being missed. A couple of days there was a very similar question: https://github.com/checkpoint-restore/criu/issues/2366

Take a look at that. Hope that helps.

**Comment by HFourier** [comment]
> @HFourier Adding comments to tickets which are already closed have a high chance to being missed. A couple of days there was a very similar question: [checkpoint-restore/criu#2366](https://github.com/checkpoint-restore/criu/issues/2366)
> 
> Take a look at that. Hope that helps.

Thanks, I will try.
