### ISSUE TITLE
crictl : exec async use spdy.

### ISSUE THREAD

**Issue by jokemanfire** [kubernetes-sigs/cri-tools#1392]
#### What would you like to be added:
I've found exec async  use SPDY protocol.  Is this protocol ? [spdy](https://www.chromium.org/spdy/)
#### Why is this needed:
SPDY is deprecated. there's some plans to modify the protocol, such as HTTP 2?

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes-sigs/cri-tools/issues/1296

**Comment by jokemanfire** [comment]
> * [when we transition from SPDY to WebSockets in exec and attach #1296](https://github.com/kubernetes-sigs/cri-tools/issues/1296)

thanks,but don't we consider completely abandoning the spdy protocol?

**Comment by saschagrunert** [comment]
> thanks,but don't we consider completely abandoning the spdy protocol?

Thank you for the question @jokemanfire, I assume we will consider that at some later point, yes.

**Comment by jokemanfire** [comment]
> > thanks,but don't we consider completely abandoning the spdy protocol?
> 
> Thank you for the question @jokemanfire, I assume we will consider that at some later point, yes.

I understand. If there are any related plans, I would be happy to participate

**Comment by saschagrunert** [comment]
Thank you, I'm closing this one here since there is nothing to be done right now.
