### ISSUE TITLE
Is cri-tools version info current?

### ISSUE THREAD

**Issue by buckaroogeek** [kubernetes-sigs/cri-tools#1398]
#### What happened:

Installed cri-o 1.29.1 and cri-tools 1.29.0 on Fedora 39 vm.

Executed ```sudo crictl version``` and received the following output:
```
[bgsmith@testf39 ~]$ sudo crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.29.1
RuntimeApiVersion:  v1
```

#### What you expected to happen:

I expected ```Version:``` to be something reflecting the release tag, e.g. ```Version: 0.1.29``` or ```Version: 1.29``` but perhaps this Version is something else?

#### How to reproduce it (as minimally and precisely as possible):
1. Start a fedora 39 machine.
2. Install cri-o and cri-tools rpms (the source I used: https://copr.fedorainfracloud.org/coprs/buckaroogeek/copr-k8s-1.29/)
3. Run ```sudo crictl version``` at command line on fedora machine

#### Environment:

- Container runtime or hardware configuration: cri-o default: runc
- OS (e.g: `cat /etc/os-release`): 
- NAME="Fedora Linux"
VERSION="39 (Cloud Edition Prerelease)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Cloud Edition Prerelease)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-05-14
VARIANT="Cloud Edition"
VARIANT_ID=cloud

- Kernel (e.g. `uname -a`):
- Linux testf39 6.5.2-301.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Sep 11 18:12:33 UTC 2023 x86_64 GNU/Linux

- Others:

**Comment by saschagrunert** [comment]
I assume the packages are not injecting the version correctly: https://github.com/kubernetes-sigs/cri-tools/blob/d42ffd46ec596ecd801f8ba8b6b6d5a558a4621a/Makefile#L39

Do you mind reaching out to the package maintainers?

**Comment by buckaroogeek** [comment]
> I assume the packages are not injecting the version correctly:
> 
> https://github.com/kubernetes-sigs/cri-tools/blob/d42ffd46ec596ecd801f8ba8b6b6d5a558a4621a/Makefile#L39
> 
> Do you mind reaching out to the package maintainers?

Thank you. I will check into the spec file and propose a pull request. For @haircommander - FYI

**Comment by buckaroogeek** [comment]
So this has been an interesting exercise! :)   I was not paying really close attention to cri-tools -h output. ```crictl version``` is all runtime version information from the server. ```crictl --version``` or ```crictl -v``` displays version info for crictl. 

There is indeed a bug in the Fedora spec file such that ```crictl -v``` currently displays ```crictl version unknown```. I have an update in hand which updates the ```unknown``` value to the current version in the spec file.

The ```Version: 0.1.0``` from the server (cri-o is what I am testing with) is still perplexing. But not something that needs to be answered here.

Thanks again @saschagrunert. This will be a useful update for the fedora package.

**Comment by saschagrunert** [comment]
Ah yes, `version` is the RPC. 😊
