### ISSUE TITLE
 Image pull progress 

### ISSUE THREAD

**Issue by ghorbani-ali** [kubernetes-sigs/cri-tools#1401]
#### What would you like to be added:
Show the total size and progress of the total downloaded size when pulling the image

#### Why is this needed:
When we pull the images, nothing is displayed about the image size, how many layers are there, or how much is downloaded. This can be most user-friendly.
However, from my study of the contribution documents, I found that to start working on such a change, I need to get approval from your team first.

May I work on this? Any insight?

**Comment by SergeyKanzhelev** [comment]
What CRI APIs do you want to use for this? From k8s SIG Node we had a few attempts to add new APIs to increase transparency in download progress, but as far as I remember we didn't get far on this.

For the size - you likely will also need a new API call. Or you know a way?

I commented without looking at API, it was long time I checked them.

**Comment by saschagrunert** [comment]
This is related to https://github.com/kubernetes/enhancements/issues/3542

**Comment by ghorbani-ali** [comment]
@SergeyKanzhelev Thanks for your reply.
First, I was wondering if this matter is acceptable to you. After your response, I also briefly reviewed the API project. I found functions there related to image size and returning information. I divided the work into two main parts:

    Retrieving and displaying the total image size.
    Size in the process of downloading.

For the first part, as I mentioned, there are already functions in place, but I need to examine them more closely. For the second part, I currently have no ideas and need more time to investigate. Are you in agreement with the overall plan? I would appreciate it if you could share your thoughts.

**Comment by saschagrunert** [comment]
@ghorbani-ali you can't really retrieve the image size if the pull is still in progress, means we need a dedicated API for that. CRI-O emits a bunch of events and logs during pull to outline the progress, but that's nothing standardized. I don't see much movement for this issue unfortunately other than trying to hook into the runtime.
