### ISSUE TITLE
kubeadm join fails on Windows  return    getting status of runtime: invalid character 'P' in string escape code

### ISSUE THREAD

**Issue by wzyjhrl** [kubernetes-sigs/cri-tools#1426]
kubeadm join  fails
error like 
time="2024-05-11T07:31:56+08:00" level=fatal msg="getting status of runtime: invalid character 'P' in string escape code"

run  crictl.exe info
show error like this
time="2024-05-11T07:31:56+08:00" level=fatal msg="getting status of runtime: invalid character 'P' in string escape code"

Follow the instructions to install contrainerd

https://github.com/containerd/containerd/blob/main/docs/getting-started.md

Stop-Service containerd
$Version="1.7.13"	# update to your preferred version
$Arch = "amd64"	# arm64 also available
curl.exe -LO https://github.com/containerd/containerd/releases/download/v$Version/containerd-$Version-windows-$Arch.tar.gz
tar.exe xvf .\containerd-$Version-windows-amd64.tar.gz
Copy-Item -Path .\bin -Destination $Env:ProgramFiles\containerd -Recurse -Force
$Path = [Environment]::GetEnvironmentVariable("PATH", "Machine") + [IO.Path]::PathSeparator + "$Env:ProgramFiles\containerd"
[Environment]::SetEnvironmentVariable( "Path", $Path, "Machine")
$Env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")

containerd.exe config default | Out-File $Env:ProgramFiles\containerd\config.toml -Encoding ascii
Get-Content $Env:ProgramFiles\containerd\config.toml
containerd.exe --register-service
Start-Service containerd

#### Environment:

Microsoft Windows [version 10.0.17763.5696]
crictl  version  1.30.0
contrainerd RuntimeVersion:  v1.7.13

![image](https://github.com/kubernetes-sigs/cri-tools/assets/2156327/4c409db0-3216-49f3-8508-7495d20d70e8)

**Comment by SergeyKanzhelev** [comment]
Not a new issue. I see mentions: https://github.com/kubernetes/kubernetes/issues/110626 and https://eviatargerzi.medium.com/installing-kubernetes-with-a-windows-node-a256f47ad85a.

If you have a repro, maybe you can collect more information:
- Containerd logs (as verbose as you can go)
- Run crictl in verbose mode

**Comment by saschagrunert** [comment]
I assume this is resolved now.
