### ISSUE TITLE
Publish crictl as a container image

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes-sigs/cri-tools#1428]
#### What would you like to be added:

A container image that contains the `crictl` binary

#### Why is this needed:

EKS recommends to create a container when debugging node-level issues: https://github.com/awslabs/amazon-eks-ami/issues/876#issuecomment-1062971771

In order to do this, an image with `crictl` is needed.

**Comment by saschagrunert** [comment]
@alvaroaleman thank you for the request! Maintaining the image adds more overhead on our end, so I'm wondering if it's really beneficial compared to download the binary directly.

**Comment by nmaguiar** [comment]
@alvaroaleman I went through the same and, after not finding one I liked, I built the image and the automation to keep it updated. Image: nmaguiar/imgutils:lite; Source: https://github.com/nmaguiar/imgutils

**Comment by BenTheElder** [comment]
You could fetch the static go binary from an image with wget/curl FWIW.

I would recommend EKS publish an image intended to debug their nodes that contains all relevant utils instead of _just_ a crictl image.

**Comment by saschagrunert** [comment]
I agree, closing this request for now. Feel free to reopen if we missed some critical aspect.
