### ISSUE TITLE
cannot pull image using crictl 

### ISSUE THREAD

**Issue by XP2600-hub** [kubernetes-sigs/cri-tools#1530]
#### What happened: I try to pull image using crictl:
crictl pull "docker.io/calico/kube-controllers:v3.25.0"

#### How to reproduce it (as minimally and precisely as possible):
crictl pull "docker.io/calico/kube-controllers:v3.25.0"

#### Environment:

- Container runtime or hardware configuration: cri-o
- OS (e.g: `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`): 6.5.0-45-generic 
- Others:

**Comment by SergeyKanzhelev** [comment]
Can you share the following:

- Version of CRI-O
- Version of crictl
- crictl verbose logs
- Logs from CRI-O
- any mirrors that were configured for docker.io in CRI-O configuration (there are typically mirrors are configured for it)

I don't have CRI-O handy to test, but it works with containerd

**Comment by kwilczynski** [comment]
Works fine with CRI-O:

```console
INFO[2024-07-25 17:32:26.096806574Z] Pulled image: docker.io/calico/kube-controllers@sha256:095484425365e4eac24abfdd28ba14d133ffcc782c36b5d4f08533ef75ee91e4  file="server/image_pull.go:122" id=1caf1150-2ce2-4d86-93bc-4e453d26bfc4 name=/runtime.v1.ImageService/PullImage
```

CRI-O version:

```console
crio version Version:        1.31.0
   GitCommit:      59d4b9a3e28986365e9ba0fea1849e5d49cddfdc
   GitCommitDate:  2024-07-25T15:26:19Z
   GitTreeState:   dirty
   BuildDate:      2024-07-25T15:51:53Z
   GoVersion:      go1.22.5
   Compiler:       gc
   Platform:       linux/amd64
   Linkmode:       dynamic
   BuildTags:      
     containers_image_ostree_stub
     apparmor
     containers_image_openpgp
     seccomp
     selinux
     exclude_graphdriver_devicemapper
   LDFlags:          unknown
   SeccompEnabled:   true
   AppArmorEnabled:  true
```

**Comment by kwilczynski** [comment]
Related:

- https://github.com/kubernetes-sigs/cri-tools/issues/1463

**Comment by saschagrunert** [comment]
I don't think that's an issue with cri-tools, isn't it? Can we close this one then?

**Comment by XP2600-hub** [comment]
Apologizes seems more like internet issue, strangely docker pull was working on other machine, maybe critools have more strict timeout or something, yes can be closed.
