### ISSUE TITLE
Tôi bị ko làm bài tập

### ISSUE THREAD

**Issue by tienngaunhatquadat** [kubernetes-sigs/cri-tools#1731]
#### Environment:

- Container runtime or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by feiskyer** [comment]
@tienngaunhatquadat what does this mean? could you provide the details of your problem?

**Comment by kwilczynski** [comment]
/close

Feel free to re-open should there be anything of value to report as a bug.
