### ISSUE TITLE
json to yaml doesn't preserve order.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-sigs/cri-tools#210]
The generated yaml does not follow the original order. This doesn't seem to be a good user experience.

**Comment by miaoyq** [comment]
@Random-Liu 
The output of `json/yaml.Unmarshal(data, &interface_object)` is a map, but map is a unordered fields, 
so the output of `json/yaml.Marshal(map)` will order by `key`.

If we want to keep the order, we need convert the buffer object to yaml directly, but this conflicts with #154.

**Comment by miaoyq** [comment]
See: https://github.com/go-yaml/yaml/issues/275#issuecomment-322000292

**Comment by Random-Liu** [comment]
@miaoyq Yeah, I think it's fine for now. :)
Just file the issue here so that in the future if we have strong requirement for this, we could come back and discuss/address.
