### ISSUE TITLE
Add validation support for windows containers

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cri-tools#223]
We should add validation support for windows containers, includes

- Fix building for windows
- Validation adjusting for windows containers

cc @JiangtianLi

**Comment by JiangtianLi** [comment]
Thanks, @feiskyer. Let me know if I can help.

**Comment by yujuhong** [comment]
> We should add validation support for windows containers, includes
> 
> * Fix building for windows
> * Validation adjusting for windows containers

@feiskyer has anything been done in these areas?

**Comment by feiskyer** [comment]
The travis CI doesn't support Windows Server 2019, so we still need to find other infra for running those tests.
