### ISSUE TITLE
critest: updateRuntimeConfig

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cri-tools#23]

**Comment by feiskyer** [comment]
Seems only kubenet supports updateRuntimeConfig interface in current releases, other cni plugins just omits this change in dockershim.

I think other runtimes may not support this feature because there is no update interface in CNI. 

@Random-Liu @mrunalp @mikebrow @dcbw Any ideas on this?

**Comment by mikebrow** [comment]
Well we could help these guys out:
https://github.com/containernetworking/cni/issues/89
