### ISSUE TITLE
crictl stats not giving kata containers resource usage.

### ISSUE THREAD

**Issue by yadavkkumar** [kubernetes-sigs/cri-tools#328]
## What happened?

Trying to get container resource usage using `crictl stats` but it is fetching resource usage of runc containers but not of kata containers.

## What you expected to happen?
Like `crictl ps` and `crictl pods` gives list of all the containers (both runc and kata-containers) and pods, similarly `crictl stats` should give resource usage of all the containers.

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):
```
Linux tcs07 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 6_64 x86_64 GNU/Linux
```

- **Others**:
```
crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.11.0-dev
RuntimeApiVersion:  v1alpha1
```

**Comment by feiskyer** [comment]
@yadavkkumar crictl gets stats by `ListContainerStats()`. Has the interface been implemented in kata containers?

**Comment by yadavkkumar** [comment]
@feiskyer 
The `ListContainerStats()` interface is implemented in crictl. But there is no interface like `ListContainerStats()` in runc and kata-containers. Can you tell me why we need this interface in runc and kata-containers. 
We have this `crictl ps` command which implements ListContainers() and gives all the container running in runc and kata-runtime. Similarly why `crictl stats` is giving only stats of the runc container.

**Comment by feiskyer** [comment]
@yadavkkumar Oh, sorry, you are using cri-o, `ListContainerStats()` should be implemented within cri-o. 

@runcom Seems container stats only support runc runtime within cri-o?

cc @@gnawux (kata containers maintainer)

**Comment by runcom** [comment]
@feiskyer @yadavkkumar we're still relying on cadvisor for that and haven't yet implemented it. We're working on it though

**Comment by yadavkkumar** [comment]
@feiskyer @runcom  Thanks

**Comment by feiskyer** [comment]
Close the issue since it's actually a cri-o issue.
