### ISSUE TITLE
Why isn't critest bundled in the release downloads?

### ISSUE THREAD

**Issue by luxas** [kubernetes-sigs/cri-tools#330]
Just curious, as it seems strange this repo is building two cmds, but only shipping one.
Intentional or not?

@feiskyer @Random-Liu

**Comment by chuckha** [comment]
The release ships both: https://github.com/kubernetes-incubator/cri-tools/releases/download/v1.11.0/crictl-v1.11.0-linux-amd64.tar.gz and https://github.com/kubernetes-incubator/cri-tools/releases/download/v1.11.0/critest-v1.11.0-linux-amd64.tar.gz

Unless you're asking why they aren't sipped in the same tarball and maybe call it cri-tools?

**Comment by luxas** [comment]
> Unless you're asking why they aren't sipped in the same tarball and maybe call it cri-tools?

Exactly that was my point. Apparently I'm blind though, as I didn't even see https://github.com/kubernetes-incubator/cri-tools/releases/download/v1.11.0/critest-v1.11.0-linux-amd64.tar.gz :joy:

**Comment by feiskyer** [comment]
There're not bundled together because crictl supports more platforms today. It's more clear of separating them with different tarballs.
