### ISSUE TITLE
Add testing for crictl

### ISSUE THREAD

**Issue by yujuhong** [kubernetes-sigs/cri-tools#364]
The crictl command-line tool is used by components such as kubeadm, and is also shipped by default on the Kubernetes nodes in GCE.

We should have testing for it to catch bugs. One option is to add a fake runtime implementation. Any thoughts/suggestions?

(We can also include a crictl test in kubernetes, but the turn-around time for bug fix would be long...)

/cc @Random-Liu

**Comment by feiskyer** [comment]
+1, I think we can use dockershim to test crictl, which is also used for critest

**Comment by feiskyer** [comment]
nop, test functionality of crictl itself, e.g. the expected output of each commands.

**Comment by xlgao-zju** [comment]
> e.g. the expected output of each commands.

I mean maybe we can use the `ginkgo` framework in the test of crictl too?

**Comment by Random-Liu** [comment]
Actually we can use crictl to write CRI validation test, but that requires a lot of code refactoring. :p

**Comment by yujuhong** [comment]
kubectl tests are essentially a pile of shell scripts. I wonder if there are better ways to do this.

**Comment by yujuhong** [comment]
> Actually we can use crictl to write CRI validation test, but that requires a lot of code refactoring. :p

We should still keep the existing CRI validation test, since kubelet doesn't use crictl to talk to CRI shims ;)

**Comment by feiskyer** [comment]
> FWIW, We use crictl directly in CRI-O integration tests.

👍 [bats](https://github.com/bats-core/bats-core) is used in cri-o. Seems it's much better than direct shell scripts.

**Comment by feiskyer** [comment]
@saschagrunert there's no tests for crictl yet, would you like to work on it?

**Comment by saschagrunert** [comment]
> @saschagrunert there's no tests for crictl yet, would you like to work on it?

Sure, do we want to use bats (like in CRI-O), or ginkgo (like in Kubernetes). I tend to go with ginkgo, since this dependency is already available.

**Comment by feiskyer** [comment]
is ginkgo working well for CLI tests?

**Comment by saschagrunert** [comment]
> is ginkgo working well for CLI tests?

Yes, with gomega’s [gexec](https://onsi.github.io/gomega/#gexec-testing-external-processes), I’ll prepare a PR.

**Comment by hickeyma** [comment]
@saschagrunert @feiskyer @yujuhong Just wondering if this is covered by the work in #613?

**Comment by saschagrunert** [comment]
> @saschagrunert @feiskyer @yujuhong Just wondering if this is covered by the work in #613?

Hm partially, it was more about e2e testing the functionality of crictl.

**Comment by feiskyer** [comment]
yea, not finished yet.

**Comment by hickeyma** [comment]
ok, thanks for the feedback @saschagrunert @feiskyer
