### ISSUE TITLE
release-1.12 fails to build

### ISSUE THREAD

**Issue by lsm5** [kubernetes-sigs/cri-tools#395]
Trying to build from source and I see this:

    # github.com/kubernetes-sigs/cri-tools/vendor/k8s.io/client-go/transport
    src/github.com/kubernetes-sigs/cri-tools/vendor/k8s.io/client-go/transport/round_trippers.go:437:9: undefined: strings.Builder

/cc @mrunalp

**Comment by lsm5** [comment]
seems I was building with an older golang. I'll try with a newer build and report back.

**Comment by feiskyer** [comment]
@lsm5 👍 Let me if you still have problems.
