### ISSUE TITLE
Support "crictl pods --name filter" with Metadata name.

### ISSUE THREAD

**Issue by rjaini** [kubernetes-sigs/cri-tools#403]
if I use following pod config to create pod:
{
    "metadata": {
        "name": "linux-sandbox",
        "namespace": "default",
        "attempt": 1
    },
    "labels": {
        "sandbox-platform": "linux/amd64"
    }
}

crictl pods command return following output
POD ID              CREATED             STATE               NAME                    NAMESPACE           ATTEMPT
3e696d25f77a7       24 hours ago        Ready               linux-sandbox   default             1

Now when I try to search the pod with above name 
crictl pods --name linux-sandbox 

I see no output. Ideally I should be able to get above pod.

But If I add below two labels with same value then things works.
io.kubernetes.pod.name 
io.kubernetes.pod.namespace 

Ideally I should also be able to search by metadata name.

**Comment by feiskyer** [comment]
@rjaini `crictl pods --name` supports regexp, could you try with that?

**Comment by jterry75** [comment]
@feiskyer - That's not what he is saying.
```JSON
{
    "metadata": {
        "name": "linux-sandbox",
        "namespace": "default",
        "attempt": 1
    },
    "labels": {
        "sandbox-platform": "linux/amd64"
    }
}
```
```sh
crictrl pods --name linux-sandbox
```
Returns nothing.

--
But
```JSON
{
    "metadata": {
        "name": "linux-sandbox",
        "namespace": "default",
        "attempt": 1
    },
    "labels": {
        "sandbox-platform": "linux/amd64",
        "io.kubernetes.pod.name": "test-name",
        "io.kubernetes.pod.namespace": "test-namespace"
    }
}
```
```sh
crictrl pods --name test-name
```
Returns the POD as expected.

--

The ask is that `--name` and `--namespace` support matching the `metadata.Name` and `metadata.Namespace` and not just the labels `io.kubernetes.pod.name` and `io.kubernetes.pod.namespace`.

**Comment by Random-Liu** [comment]
This makes sense to me. We don't need to use labels for metadata that already exists in the pod config.

**Comment by feiskyer** [comment]
@rjaini Oops, you are right.

**Comment by jterry75** [comment]
Thanks!

**Comment by rjaini** [comment]
Thanks.
