### ISSUE TITLE
Support something similar to "docker load"?

### ISSUE THREAD

**Issue by luxas** [kubernetes-sigs/cri-tools#412]
That maybe would make sense in some scenarios where you can't pull, but have to side-load images
cc @feiskyer @yujuhong

**Comment by feiskyer** [comment]
I'm afraid this is not possible since cri-tools only talks with CRI.

@luxas Which container runtime are you using?

**Comment by luxas** [comment]
> @luxas Which container runtime are you using?

no specific one. I was just thinking if this was possible using the current CRI spec. No worries.

**Comment by Random-Liu** [comment]
Currently, for containerd, you can load image with either `ctr cri load` or `ctr import`. And we may deprecate `ctr cri load` in the future.

**Comment by vrothberg** [comment]
> > @luxas Which container runtime are you using?
> 
> no specific one. I was just thinking if this was possible using the current CRI spec. No worries.

The issue just popped up in my mails. Since the CRI doesn't support that, we need to work around that. When using CRI-O there is `skopeo copy` and `podman load`.

**Comment by feiskyer** [comment]
yep, this can only be done within container runtime. 

Since this is not a supported scenario from CRI, let's close the issue.

/close
