### ISSUE TITLE
Is there a way to get container diff?

### ISSUE THREAD

**Issue by nrvnrvn** [kubernetes-sigs/cri-tools#418]
`docker diff` is a useful tool to get the diff between the running state of a container and it’s image. It is especially useful when you want to run some third party containerized app with the  read-only rootfs and need to understand how the internals work.

Is there any recommended way to check the “diff” for containerd?

**Comment by feiskyer** [comment]
@Random-Liu Any insights on this?

**Comment by Random-Liu** [comment]
> Is there any recommended way to check the “diff” for containerd?

It is possible to add a `diff` command in `ctr`.

**Comment by feiskyer** [comment]
> It is possible to add a diff command in ctr.

Agreed. It could be done in container runtime, but not in crictl. crictl doesn't know the detailed container manifests.

/close
