### ISSUE TITLE
QUESTION: What is uid?

### ISSUE THREAD

**Issue by dungdm93** [kubernetes-sigs/cri-tools#420]
When I work with `crictl`, I got something like:
```
$ cat pod-config.json
{
    "metadata": {
        "name": "nginx-sandbox",
        "namespace": "default",
        "attempt": 1,
        "uid": "hdishd83djaidwnduwk28bcsb"
    },
    "logDirectory": "/tmp",
    "linux": {
    }
}
```
So, my question is: What is `metadata.uid` and What are its available values?

**Comment by dungdm93** [comment]
@feiskyer As far as I know from [this](https://kubernetes.io/docs/concepts/workloads/pods/pod/#what-is-a-pod), `uid` is pod unique ID. However, when I check it with `crictl pods`, I got different id:
```
$ crictl pods
POD ID              CREATED             STATE               NAME                NAMESPACE           ATTEMPT
12e7cf8d482d0       9 hours ago         Ready               nginx-sandbox       default             1
```

**Comment by feiskyer** [comment]
`Pod ID` is different from UID, UID is part of metadata, while Pod ID is the container ID from runtime.

**Comment by liticia-hub** [comment]
@dungdm93 can you tell me please what does metadata.uid represent and what are its available values ? 
thank you

**Comment by sarangjo** [comment]
@greatjob-hub Kubernetes generates a unique ID for all objects in the system, this is the UID that shows up in the metadata: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids
