### ISSUE TITLE
`crictl stats` doesn't check if user is root

### ISSUE THREAD

**Issue by lsm5** [kubernetes-sigs/cri-tools#426]
$ crictl stats
    FATA[0000] get container stats failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable

but `sudo crictl stats` works. It'd help if crictl would check if user is root and complain otherwise.

cc @mrunalp

**Comment by lsm5** [comment]
filed https://github.com/kubernetes-sigs/cri-tools/pull/427

**Comment by saschagrunert** [comment]
Hey 👋, I guess it should be possible to run crictl without being root since it depends on the permissions of the cri-o connection socket.

It would be cool if we could change that and run cri-o under some dedicated user/group.

**Comment by mrunalp** [comment]
@saschagrunert That's a good point and valid for rootless scenarios. Maybe we can check if we can access the socket instead?

**Comment by saschagrunert** [comment]
Yep that would be great, I guess cri-o will need some configuration extensions for that.

**Comment by lsm5** [comment]
On Mon, Jan 21, 2019 at 10:31:52AM -0800, Mrunal Patel wrote:
> @saschagrunert That's a good point and valid for rootless scenarios. Maybe we can check if we can access the socket instead?
> 

ack, I'll check on that, thanks

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by saschagrunert** [comment]
> ack, I'll check on that, thanks

I took my freedom toncteate the issue in cri-o. Are you going to work on that? :)

**Comment by feiskyer** [comment]
I think this could be closed now.

/close
