### ISSUE TITLE
crictl completion for zsh

### ISSUE THREAD

**Issue by cpointner** [kubernetes-sigs/cri-tools#435]
#213 states that installing the completion using `source <(crictl completion)` works for both bash and zsh. Unfortunately this is only true if `bashcompinit` has been loaded in your zshrc. Depending on your zsh setup this might or might not be the case when you source the output of the completion sub-command.

As far as i undertstand this could be fixed by adding the contents of this [file](https://github.com/urfave/cli/blob/master/autocomplete/zsh_autocomplete) to [cmd/crictl/completion.go](../blob/master/cmd/crictl/completion.go) and add a parameter to the completion sub-command that selects between bash or zsh.

**Comment by Random-Liu** [comment]
SG. Do you want to send a PR for this? :)
