### ISSUE TITLE
unknown service runtime.v1alpha2.ImageService &Unimplemented desc = unknown service api.v1.CRIPluginService

### ISSUE THREAD

**Issue by Apokleos** [kubernetes-sigs/cri-tools#436]
Hi, when I execute cmd: crictl images, something goes wrong. It will output error info as "FATA[0000] listing images failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService" 

ENV:
OS: Centos7.6,
Kernel Linux 3.10.0-957.5.1.el7.x86_64 x86_64
Setup crictl, containerd and runc Steps:
(1) containerd
wget https://github.com/containerd/containerd/releases/download/v1.2.0/containerd-1.2.0.linux-amd64.tar.gz
tar -xvf containerd-1.2.0.linux-amd64.tar.gz -C /usr/local/
(2) runc
wget -O /usr/local/sbin/runc https://github.com/opencontainers/runc/releases/download/v1.0.0-rc6/runc.amd64
chmod +x /usr/local/sbin/runc
(3) crictl
VERSION="v1.13.0"
wget https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-$VERSION-linux-amd64.tar.gz
tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/local/bin
rm -f crictl-$VERSION-linux-amd64.tar.gz
(4) config containerd.service
curl -o /etc/systemd/system/containerd.service https://raw.githubusercontent.com/containerd/cri/master/contrib/systemd-units/containerd.service
systemctl daemon-reload
systemctl enable containerd
systemctl start containerd
systemctl status containerd
(5) config crictl.yaml
cat /etc/crictl.yaml
runtime-endpoint: unix:///run/containerd/containerd.sock
image-endpoint: unix:///run/containerd/containerd.sock
timeout: 10
debug: true
...
THEN
containerd --version
crictl --version 
runc --version 
Test will be OK.
But, when I try the cmd "crictl images" , it will failed. and "ctr cri load pause-3.1.tar" will also fail. 
ERROR msg as below:

$# ctr cri load pause-3.1.tar
ctr: failed to load image: rpc error: code = Unimplemented desc = unknown service api.v1.CRIPluginService
$# crictl images
FATA[0000] listing images failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService

**Comment by Apokleos** [comment]
problem occurs at the place /etc/containerd/config.toml, 
[plugins.cri.containerd]
      snapshotter = "overlayfs" --> "native"
It works successfully, now!

**Comment by cusri-admin** [comment]
这个方法很好

**Comment by cusri-admin** [comment]
very good

**Comment by lvyangxu** [comment]
snapshotter = "overlayfs" --> "native"
it works !
