### ISSUE TITLE
[Feature request]: please support changing image tag and push images

### ISSUE THREAD

**Issue by dinfer** [kubernetes-sigs/cri-tools#438]
I'm planing using crictl instead of docker for some common operations. Is there any plan to make crictl be able to tag image and push image to a registry?

**Comment by Random-Liu** [comment]
That is not in scope.

`crictl` is only used for Kubernetes node debugging, it is not a replacement of docker.

For building/tagging images, please continue using docker.

**Comment by feiskyer** [comment]
Agreed with @Random-Liu. crictl is only talking with kubernetes CRI interface, it's not a replacement of container runtime's one.

/close

**Comment by matti** [comment]
well, now kubernetes is removing docker https://github.com/kubernetes/kubernetes/pull/94624

would be handy to tag and push in node during that famous troubleshooting 

#640

**Comment by zoulux** [comment]
It's very sad, I didn't want to install Docker

**Comment by yiya1989** [comment]
I didn't want to install Docker too
