### ISSUE TITLE
Tests expect specific SELinux policies to be enabled on host

### ISSUE THREAD

**Issue by sashayakovtseva** [kubernetes-sigs/cri-tools#439]
Running validation tests on SELinux host results in two errors here
- selinux mount label should persist when container is privileged
- check selinux process label for privileged and unprivileged containers

It seems that those tests rely on host configuration? I assume some specific policies need to be installed to make them pass. Could you help with that? Any related information will be very helpful!

**Comment by feiskyer** [comment]
@sashayakovtseva Which container runtime are you targeted?

**Comment by sashayakovtseva** [comment]
@feiskyer [Singularity](https://github.com/sylabs/singularity) runtime

**Comment by sashayakovtseva** [comment]
Hello @feiskyer, any updates on this issue? Maybe you can point to any instructions with expected labels to be on host? Why tests check that particular labels? Any link to documentation of tests behavior will be extremely appreciated! Thanks in advance

**Comment by feiskyer** [comment]
For the test cases, could you have a look at the validation codes [here](https://github.com/kubernetes-sigs/cri-tools/blob/master/pkg/validate/selinux_linux.go)? It doesn't seem to require pre-configured policies on the host.

Maybe you can share the detailed failure logs, so that we could understand why it's failing?

**Comment by sashayakovtseva** [comment]
@feiskyer Sure I have taken a look at code :)
Two errors we have are: `expect "object_r:container_file_t" in mountinfo` and `expect "system_r:spc_t" in proc attr`
