### ISSUE TITLE
Crictl config cannot set debug to false

### ISSUE THREAD

**Issue by liujing66** [kubernetes-sigs/cri-tools#440]
Issue Description:
When I tested the sub option of crictl config, I found that "crictl config" cannot set debug to false。

# crictl config --get debug
true

# crictl config debug false
FATA[0000] use true|false for debug 

It seems like a bug,the code 118-129 lines ，the if statement is missing the setting for value=“false”
		case "debug":
			var debug bool
			if value == "true" {
				debug = true
			} else {
				logrus.Fatal("use true|false for debug")
			}
config.Debug = debug

My crio verison is:
# crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.12.0-dev
RuntimeApiVersion:  v1alpha1

**Comment by Random-Liu** [comment]
Feel free to send a fix for the bug. :)
