### ISSUE TITLE
Is cni needed when just using containerd?

### ISSUE THREAD

**Issue by caoruidong** [kubernetes-sigs/cri-tools#441]
Without k8s, just containerd + crictl.
`crictl runp sandbox.json` returns
`
FATA[0000] run pod sandbox failed: rpc error: code = Unknown desc = failed to setup network for sandbox "282a6d46182a7d0ed1ddda7dd6c5ab65c25145c0534dd34c0701a9f0d6d23945": cni plugin not initialized
`
There is no file in /etc/cni/net.d/

**Comment by feiskyer** [comment]
from the logs, it is. @Random-Liu

**Comment by caoruidong** [comment]
It works after reboot.

**Comment by Random-Liu** [comment]
Yeah you still need cni when using containerd + crictl.

**Comment by caoruidong** [comment]
Got it. Thanks you all
