### ISSUE TITLE
'crictl status --label ' operation does not work .

### ISSUE THREAD

**Issue by liujing66** [kubernetes-sigs/cri-tools#448]
Issue Description:
When I want to dispaly the stats of a particular label's container in the kubenet environment, 'crictl status --label ' operation does not work .

All containers is running on the current environment .

# crictl stats | wc -l
43

I want to see the current consumption of the container in the openshift-sdn project.
The expected output should be two pieces of information， but actually output all the containers.

# crictl stats --label io.kubernetes.pod.namespace=openshift-sdn | wc -l
43

# crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.12.6-1.rhaos4.0.git2f0cb0d.el7
RuntimeApiVersion:  v1alpha1

# oc version
Client Version: version.Info{Major:"4", Minor:"0+", GitVersion:"v4.0.22", GitCommit:"219bbe2f0c", GitTreeState:"", BuildDate:"2019-03-10T22:23:11Z", GoVersion:"", Compiler:"", Platform:""}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4+299da2c", GitCommit:"299da2c", GitTreeState:"clean", BuildDate:"2019-03-15T03:24:46Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by feiskyer** [comment]
Could you try with crictl v1.12.0 for kubernetes v1.12?
