### ISSUE TITLE
Missing cri-tools package for Ubuntu Bionic 18.04 in the PPA repository

### ISSUE THREAD

**Issue by jqueuniet** [kubernetes-sigs/cri-tools#449]
The Project Atomic PPA repository is missing a cri-tools package for Ubuntu Bionic, it is only available for Xenial right now. A similar issue was previously filled for the cri-o package in the cri-o repository.

https://launchpad.net/~projectatomic/+archive/ubuntu/ppa?field.series_filter=bionic

I would be nice to have, as it would simplify cri-o support in Kubespray.

cc @lsm5

**Comment by feiskyer** [comment]
Not sure how is those package built. @jqueuniet @lsm5 Are you maintaining those packages?

**Comment by lsm5** [comment]
On Tue, Mar 19, 2019 at 06:59:16AM -0700, Pengfei Ni wrote:
> Not sure how is those package built. @jqueuniet @lsm5 Are you maintaining those packages?
> 

Yup, this one's on me. Didn't see a better place to report this issue, so hope
it's alright here.

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by feiskyer** [comment]
@lsm5 cool. then could you build the image there?

**Comment by feiskyer** [comment]
@lsm5 any updates on this?
