### ISSUE TITLE
crictl: --runtime-endpoint doesn't handle relative paths well

### ISSUE THREAD

**Issue by tych0** [kubernetes-sigs/cri-tools#460]
It seems there is a bug with relative paths. If I do:

`strace crictl --runtime-endpoint ../foo create clowncore basic-container-config.json basic-pod-config.json`

I get:

`connect(6, {sa_family=AF_UNIX, sun_path="/foo"}, 7) = -1 ENOENT (No such file or directory)`

It shouldn't be eating the first bits of my path, I don't think.

**Comment by feiskyer** [comment]
seems the issue hasn't been fixed yet. Let's reopen it.

**Comment by knabben** [comment]
This is very confusing and relative paths are not supported at all, if the local socket resides on */run/containerd/containerd.sock*, and you set something like *--runtime-endpoint=../run/containerd/containerd.sock* it works.

But cd-ing into /run/another-folder, and using *--runtime-endpoint=../containerd/containerd.sock* does not.

The "wrong" parse comes from [here](https://github.com/kubernetes-sigs/cri-tools/blob/master/vendor/k8s.io/kubernetes/pkg/kubelet/util/util_unix.go#L120), where the url.Parse can't parse the Scheme and creates a wrong local Unix fallback:

unix://../containerd/containerd.sock (missing one slash)

So this leads to returns an incorrect final addres = "/containerd/containerd.sock" from u.Path. 

It's affecting CRI (--container-runtime-endpoint) and e2e node tests (which shares the util file below)
