### ISSUE TITLE
Howto crictl pull image with authentication flag  (podman like --authfile)

### ISSUE THREAD

**Issue by AsherShoshan** [kubernetes-sigs/cri-tools#482]

**Comment by feiskyer** [comment]
```
crictl pull --creds USERNAME[:PASSWORD]
```

**Comment by AsherShoshan** [comment]
Not this one...
where podman --authfile = xx.json

xx.json

{
        "auths": {
                "cnv-qe-02.cnvqe.lab.eng.rdu2.redhat.com": {
                        "auth": "dGVzdHVzZXI6dGVzdHBhc3N3b3Jk"
                },
                "cnv-qe-server.rhevdev.lab.eng.rdu2.redhat.com:8444": {
                        "auth": "dGVzdHVzZXI6dGVzdHBhc3N3b3Jk"
                },
                "localhost": {
                        "auth": "dGVzdHVzZXI6dGVzdHBhc3N3b3Jk"
                },
                "localhost:444": {
                        "auth": "dGVzdHVzZXI6dGVzdHBhc3N3b3Jk"
                },
                "localhost:5000": {
                        "auth": "dGVzdHVzZXI6dGVzdHBhc3N3b3Jk"
                },
                "localhost:5001": {
                        "auth": "dGVzdHVzZXI6dGVzdHBhc3N3b3Jk"
                }
                      }
}

**Comment by feiskyer** [comment]
`--authfile=xx.json` is not supported in crictl pull. Any specific cases for using auth file?

**Comment by AsherShoshan** [comment]
I want to use crictl exactly the way I use it with docker and podman.  i.e.
I have this file (config.json) and in docker put in '.docker' folder or in
podman use it with '--authfile'.
There is a secret with this format, which I want to pull without
user/password authentication (--creds)

**Comment by feiskyer** [comment]
Yep, I think podman is handling those in client side, because CRI doesn't support multiple auth credentials. crictl could be extended for such cases.

@yujuhong @mrunalp what do you think?

**Comment by coopstah13** [comment]
Can we reopen this? It is inherently insecure to put the credentials into the command line.

**Comment by Huimintai** [comment]
Can we reopen this? It is inherently insecure to put the credentials into the command line.I want to use crictl pull images with credentials like docker that put the credentials into docker/config file.

**Comment by mikebrow** [comment]
you should be able to configure the container runtime daemon that crictl is connecting to.. for example in containerd .. for docker.io login set your `/etc/containerd/config.toml` to include 
```
    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.configs]
        [plugins."io.containerd.grpc.v1.cri".registry.configs."registry-1.docker.io".auth]
          username = ""
          password = ""
```

detail:
https://github.com/containerd/containerd/blob/main/docs/cri/registry.md#configure-registry-credentials

**Comment by mikebrow** [comment]
passed in auth overrides configured auth

**Comment by mikebrow** [comment]
for crio.. I believe you set `--global-auth-file`
