### ISSUE TITLE
Becoming an owner

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/cri-tools#491]
Hey :wave:, I'd like to support you here by tackling down some issues and enhancements. I'm currently maintaining CRI-O as well so I guess it would be a good fit for me personally. Do you think that it would be possible to promote me to a maintainer? :innocent:

**Comment by feiskyer** [comment]
@saschagrunert Thanks for your great work. I'm definitely +1 for this.

cc @yujuhong @Random-Liu @mrunalp

**Comment by Random-Liu** [comment]
+1

Thanks for your work to improve the UX of `crictl`, I'm looking forward to your future contributions! :D

**Comment by yujuhong** [comment]
Thanks for contributing!

**Comment by mrunalp** [comment]
+1 from me :)

**Comment by saschagrunert** [comment]
Thank you! :tada:

**Comment by feiskyer** [comment]
Added now.
