### ISSUE TITLE
crictl rmi with force option

### ISSUE THREAD

**Issue by AsherShoshan** [kubernetes-sigs/cri-tools#504]
looking for the Docker equivalence docker rmi -f imageid.
Is there any?

**Comment by saschagrunert** [comment]
Hey @AsherShoshan, is this the same request as in https://github.com/kubernetes-sigs/cri-tools/issues/399? Do you think we can close this on if favor of it?

**Comment by AsherShoshan** [comment]
No. It's not the same.

**Comment by saschagrunert** [comment]
The Kubernetes CRI is not able to specify something like a `force` flag for image removal. For example CRI-O fails if the image is currently in use. The API states that the call should not return an error if the image has been already removed. @feiskyer, is there any expected behavior when an image is in use?

**Comment by AsherShoshan** [comment]
All,
The use case is:
If you a pod with container image  <something>:latest, and the
imagePullPolicy is "ifnotpresent" - Then you have no way to refresh the
image with a newer image.
(except for rebooting the worker node  or try find a node which image is
not pulled there... )
When the container run-time engine is Docker, you can docker rmi -f
<image-id>, and then the image will be refreshed.
So what are the options to refresh the image with cri-o
Asher

**Comment by saschagrunert** [comment]
Alright, so one approach could be to force stop the containers before actually removing the image. The problem is now that we cannot guarantee that the kubelet does not re-schedule the workloads before we actually were able to remove the image. :-/

**Comment by saschagrunert** [comment]
> All, The use case is: If you a pod with container image <something>:latest, and the imagePullPolicy is "ifnotpresent" - Then you have no way to refresh the image with a newer image.

You could pull the new image via `crictl pull` and restart the containers.

**Comment by AsherShoshan** [comment]
On Wed, Sep 4, 2019 at 4:37 PM Sascha Grunert <notifications@github.com>
wrote:

> All, The use case is: If you a pod with container image :latest, and the
> imagePullPolicy is "ifnotpresent" - Then you have no way to refresh the
> image with a newer image.
>
> You could pull the new image via crictl pull and restart the containers.
>
Do it on every node...

**Comment by abdennour** [comment]
any news here?

**Comment by saschagrunert** [comment]
@abdennour thanks for reaching out! Do you consider working on a solution around this?

**Comment by abdennour** [comment]
I am thinking about `-f` option to be added @saschagrunert
