### ISSUE TITLE
Add user flag for exec

### ISSUE THREAD

**Issue by stonith** [kubernetes-sigs/cri-tools#507]
crictl exec doesn't support a user flag (ie -u) like docker does. I believe people often use docker exec -u to debug issues in non-root containers to gain root access and unfortunately kubectl also doesn't have the [user flag](https://github.com/kubernetes/kubernetes/issues/30656) option for exec.

**Comment by buccella** [comment]
This is probably in the same boat as #571; if cri-api doesn't support it, crictl won't either.

Maybe `su` could be used as a workaround:
`crictl exec <container_id> /bin/su -s /bin/sh -c "<command>" <user>`

**Comment by saschagrunert** [comment]
@jiangxiaoqiang is there anything we can do here for you? :)
