### ISSUE TITLE
QUESTION: What's the difference betwewen `docker images` and `crictl images`?

### ISSUE THREAD

**Issue by JoeyLuffa** [kubernetes-sigs/cri-tools#554]
I was trying to integration `gVisor` and after I installed `containerd` and `crictl`, I saw all my pods are trying to load images into the images cache that `crictl images` can list. I cannot find them using `docker images`. What's the difference betwewen `docker images` and `crictl images`? Why all images moved to the `crictl images`  cache?

**Comment by saschagrunert** [comment]
Hey @JoeyLuffa :wave:, both commands are not really comparable, except that the output some contanier images.

`crictl images` connects to the gRPC server providing the Container Runtime Interface (CRI), which can be implemented by multiple container runtimes, like CRI-O, containerd or docker. It lists the images available on a kubernetes node.

`docker images` lists only the images available on the local docker store, independently if there is running kubernetes or not.

Does this make sense to you? :)

**Comment by JoeyLuffa** [comment]
@saschagrunert I see. BTW, can we have multiple different container runtimes running with the same k8s cluster?

**Comment by saschagrunert** [comment]
> @saschagrunert I see. BTW, can we have multiple different container runtimes running with the same k8s cluster?

Yes, the container runtime is only bound to the Kubelet configuration. So you’re free to use any runtime you want on a single node. :)

**Comment by JoeyLuffa** [comment]
Thanks, Close this issue now.
