### ISSUE TITLE
Cut cri-tools v1.17.0

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cri-tools#558]
work items include:

* Update kubernetes vendor to v1.17.0
* Build binaries by `make release` and update release notes

@saschagrunert @Random-Liu anything more would you like to include in this release?

@saschagrunert would you like to work on this release?

**Comment by saschagrunert** [comment]
Hey, sure I can take care of the release this time. Can anyone support me with the windows binaries? 

Otherwise I would check If I can find a windows machine somewhere.

**Comment by feiskyer** [comment]
The binaries building doesn't need a windows machine

**Comment by saschagrunert** [comment]
Sounds good, I'll take care as soon as v1.17.0 is available.

**Comment by saschagrunert** [comment]
@feiskyer do we want to maintain release-branches as well? We stopped doing that for 1.16.

**Comment by feiskyer** [comment]
since the CRI API doesn't change, we don't need to maintain a new branch.

**Comment by saschagrunert** [comment]
@feiskyer I'm ready to publish the release, but lacking permissions in this repository to edit the tags accordingly. Can you provide me the set of permissions?

**Comment by feiskyer** [comment]
@saschagrunert you need to be admin to edit tags, could you apply at [org](https://github.com/kubernetes/org)? Have you got the release notes ready? I can do tag publishing.

**Comment by saschagrunert** [comment]
> @saschagrunert you need to be admin to edit tags, could you apply at [org](https://github.com/kubernetes/org)? Have you got the release notes ready? I can do tag publishing.

I'll create the issue in the next minutes for the org. These are the notes so far:

```markdown
# cri-tools v1.17.0

cri-tools v1.17.0 mainly focuses on bug fixes and stability improvements.

# CRI CLI (crictl)

- #562 Bump cri-tools version in markdown docs
- #561 Vendor kubernetes v1.17.0
- #557 Update golang dependencies
- #556 Print the previous log of the container(just like kubectl)
- #555 Add rmi --prune command
- #553 Update README.md to contain latest version hint
- #552 Download golangci-lint via wget
- #550 Fix pod and container name filter for JSON/YAML output
- #545 Fix e2e tests by pinning CRI-O and conmon
- #544 Fixed Tim St. Clair's username
- #537 Add fish shell completion support
```

**Comment by feiskyer** [comment]
@saschagrunert let's include #563 in the release, it fixes a bug of force removal

**Comment by saschagrunert** [comment]
Sure sounds good. :)

**Comment by feiskyer** [comment]
Release cut https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.17.0.

@Random-Liu could you help to upload GCS release?

**Comment by feiskyer** [comment]
done by @Random-Liu 
/close
