### ISSUE TITLE
Documentation page for crictl container config have an invalid character in log_path

### ISSUE THREAD

**Issue by rancid-racer** [kubernetes-sigs/cri-tools#569]
Reading docs at https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md

container config has value 
`
"log_path" : "busybox/0.log"
`
correct value should be
`"log_path" : "busybox.0.log"`
The original throws an RPC error with failure to create the log file

**Comment by saschagrunert** [comment]
Hey @rancid-racer, I verified the behavior and papared a documentation fix for that.
