### ISSUE TITLE
Add flag for environment variables for exec subcommand

### ISSUE THREAD

**Issue by buccella** [kubernetes-sigs/cri-tools#571]
`crictl exec` doesn't support a way to pass environment variables for the command to be run. `docker exec` has the `--env` flag. 

This is a problem for some commands, such as etcdctl, which require an environment variable to be set to specify the API version. For scripts that need to check the status of etcd running within Kubernetes, it's convenient to `exec` into the container to run etcdctl. But this is less convenient to do when not using the docker CLI, due to the need to specify `ETCDCTL_API`.

Currently this can be worked around by invoking `su` to pass in the env variable:

`crictl exec <container_id> /bin/su -s /bin/sh -c "ETCDCTL_API=3 /usr/local/bin/etcdctl ..."`

**Comment by saschagrunert** [comment]
Hey @buccella :wave:, unfortunately the Container Runtime Interface (CRI) does not support passing custom environment variables via exec, so your workaround might be the best alternative to it.

**Comment by buccella** [comment]
Thanks for the quick reply, @saschagrunert
