### ISSUE TITLE
darwin support

### ISSUE THREAD

**Issue by bacongobbler** [kubernetes-sigs/cri-tools#573]
Note: this is a duplicate of #486, which was closed due to inactivity. Please feel free to close and re-open #486 if desired.

I noticed in the releases page that there is support for Windows and Linux distributions, but there is no macOS release available for critest or crictl. We are working on a CRI that can run natively on macOS. Is there a limitation preventing macOS support for critest/crictl, or just lack of demand?

Happy to provide a patch that adds macOS support if accepted.

**Comment by saschagrunert** [comment]
Hey @bacongobbler, yeah if we can cross compile it like the windows version then feel free to spin up a PR on that. Thanks in advance! 🙏
