### ISSUE TITLE
Create release v1.18.0

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/cri-tools#577]
Since Kubernetes v1.18.0 is released we should consider cutting v1.18.0 of cri-tools as well.

**Comment by feiskyer** [comment]
@saschagrunert would you cut the new release or let me do that?

**Comment by saschagrunert** [comment]
> @saschagrunert would you cut the new release or let me do that?

I can take care of it :)

**Comment by saschagrunert** [comment]
The changelog for v1.18.0 so far:

```markdown
# cri-tools v1.18.0

cri-tools v1.18.0 mainly focuses on bug fixes and stability improvements.

# Main Changes

- #559 Switch to urfave/cli/v2

# CRI CLI (crictl)

- #575 Add go-template option for inspect commands
- #570 Fix invalid `log_path` in docs

# CRI validation testing (critest)

- #576 Make apparmor failure test more flexible
- #574 Start container before fetching metrics
- #567 Cleanup container create test to reduce duplication
- #566 Add container stats test
```

**Comment by feiskyer** [comment]
@saschagrunert thanks. #579 merged now

**Comment by saschagrunert** [comment]
> @saschagrunert thanks. #579 merged now

We need one more: https://github.com/kubernetes-sigs/cri-tools/pull/581 I think travis is currently down, isn't it?

**Comment by saschagrunert** [comment]
Release done: https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.18.0

**Comment by feiskyer** [comment]
@saschagrunert thanks, let's update the version matrix as well #582
