### ISSUE TITLE
getting status of runtime failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService

### ISSUE THREAD

**Issue by sober-wang** [kubernetes-sigs/cri-tools#578]
# ENV
Kubernetes:  v1.13.5,v1.15.6
cri-tools: v1.15.0 ,v.1.12

# Problem
When I user `crictl stats -p <POD_ID>` ,it's tell me 

FATA[0000] get container stats failed: rpc error: code = Unknown desc = not implemented

**Comment by majst01** [comment]
Same here:

containerd: 1.2.10
crictl: 1.18.0

```
crictl -D -r unix:///run/containerd/containerd.sock info
DEBU[0000] StatusRequest: &StatusRequest{Verbose:true,} 
DEBU[0000] StatusResponse: nil                          
FATA[0000] getting status of runtime failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
```

**Comment by majst01** [comment]
after enabling cri plugin of containerd in /etc/containerd/config.toml:

```
# disabled_plugins = ["cri"]
```

everything works !

**Comment by feiskyer** [comment]
@majst01 so, this is just the configure issues from containerd?

**Comment by feiskyer** [comment]
@sober-wang which runtime are you using? is it the same issue?

**Comment by sober-wang** [comment]
> 
> 
> @sober-wang which runtime are you using? is it the same issue?
Kubernetes: v1.13.5,v1.15.6
cri-tools: v1.15.0 ,v.1.12
docker: 18.06.1-ce
containerd github.com/containerd/containerd v1.1.2

my version is low. : (

**Comment by majst01** [comment]
@feiskyer yes only configuration of containerd, cri plugin must be enabled !

**Comment by feiskyer** [comment]
@majst01 Thanks.

/close

**Comment by vedkumar-gupta** [comment]
after commenting cri plugins , issue is now resolved.
Thanks
