### ISSUE TITLE
crictl pulled image doesn't contain labels added to image previously

### ISSUE THREAD

**Issue by szberko** [kubernetes-sigs/cri-tools#584]
We built a docker image with some custom tags using `LABEL` command in Dockerfile. We deployed the image on two K8s clusters, first with Docker and second with CRI-O as CRI.
Running the command `sudo crictl inspection <image_id>`  on both clusters results with the following:

Docker:
```
$ sudo crictl inspecti fa07349b43eb1
{
  "status": {
    "id": "sha256:fa07349b43eb1753730075172bff2008cffad690ea778889f19fee5689c67efd",
    "repoTags": [
      "szberko/rabbitmq:latest"
    ],
    "repoDigests": [
      "szberko/rabbitmq@sha256:185c551390eb25f6b0b1891cf2bb7cb869efe6b7003dba07efed0f3fa179c5f2"
    ],
    "size": "181422407",
    "uid": null,
    "username": ""
  },
  "custom-metric-1": "my custom metric 1",
  "custom-metric-2": "my custom metric 2"
}
```

CRI-O:
```
$ sudo crictl inspecti fa07349b43eb1
{
  "status": {
    "id": "fa07349b43eb1753730075172bff2008cffad690ea778889f19fee5689c67efd",
    "repoTags": [
      "docker.io/szberko/rabbitmq:latest"
    ],
    "repoDigests": [
      "docker.io/szberko/rabbitmq@sha256:185c551390eb25f6b0b1891cf2bb7cb869efe6b7003dba07efed0f3fa179c5f2"
    ],
    "size": "186291975",
    "uid": null,
    "username": ""
  }
}
```

As you can see `custom-metric-1` and `custom-metric-2` are available on Docker CRI but not on CRI-O. 
Is there a way to fix this? Thanks!

**Comment by saschagrunert** [comment]
Hey @szberko :wave:, the difference between both output is that CRI-O does not use the protobuf `Info` field populating the labels there. This is more an enhancement we could add to CRI-O rather than an issue in cri-tools :)

**Comment by szberko** [comment]
@saschagrunert I think we can close this issue. As I see CRI-O already released your fix with the latest version.
Thank you for your fast response and for your contribution. ❤️ 🙏

**Comment by saschagrunert** [comment]
Awesome, thank you! :)
