### ISSUE TITLE
SELinux tests not enabled in critest release

### ISSUE THREAD

**Issue by erikwilson** [kubernetes-sigs/cri-tools#585]
While attempting to validate selinux support for a containerd/cri PR I noticed that critest does not use the selinux tag when building the release binary, which is needed as one of the steps for selinux detection here: https://github.com/kubernetes-sigs/cri-tools/blob/1b602d0bfc59737f7bb2cf6bf6f5e70d6a1885ab/pkg/validate/selinux_linux.go#L38

As a workaround I am modifying the cri-tools makefile with a command like:
```
sed -E -e 's|(\$\(GO_TEST\))|\1 -tags "${BUILDTAGS}"|' -i Makefile
```

It would be nice if cri-tools can provide official releases and building with selinux support.

**Comment by saschagrunert** [comment]
Hey @erikwilson :wave:, sounds good to me. A fix is incoming in https://github.com/kubernetes-sigs/cri-tools/pull/586

**Comment by erikwilson** [comment]
Thanks @saschagrunert! 🎉
