### ISSUE TITLE
Enable critest to use CRI server configuration file similar to crictl

### ISSUE THREAD

**Issue by hickeyma** [kubernetes-sigs/cri-tools#592]
`crictl` tool allows CRI server configuration to be set in the following ways:
- CLI flags like `--runtime-endpoint` and `image-endpoint`
- Config file as specified by CLI flag (`--config`), in default system location, or in the binary path
- default values

`critest` uses:
- CLI flags like `--runtime-endpoint` and `image-endpoint`
- default values

I think `critest` CRI server configuration should work similar to `crictl`. For example, if user configures `crictl` to use `containerd` in a config file, then `critest` should work the same without having to pass the `containerd` runtime flag to it.

**Comment by hickeyma** [comment]
If this is accepted, I would like to work on this if that's ok?

**Comment by saschagrunert** [comment]
Yes I agree they should behave the same. Feel free to open a PR for it if no other voices raise up. :)

**Comment by hickeyma** [comment]
Thanks @saschagrunert. I will push a PR soon unless someone objects in the meantime.

**Comment by hickeyma** [comment]
Pushed PR #594
