### ISSUE TITLE
Should there be a default for the CRI server endpoint?

### ISSUE THREAD

**Issue by hickeyma** [kubernetes-sigs/cri-tools#597]
Currently, the CRI server endpoint default is `dockershim.sock`. I am wondering if this makes sense as it could be `dockershim.sock` or `containerd.sock` or `cri-o.sock`?

Would it be better that the user specifies explicitly the endpoint? This way it avoids connecting unexpectedly to a running server.

**Comment by mikebrow** [comment]
hmm..
maybe 1) check if there is a command line directive or config 2) if no cli directive or config check for a list of known default endpoints and display the connections you found and a warning  3) if only one default endpoint is found use it but complain loudly 4) if two or more and one is docker.. use that as the default but announce loudly that said default is deprecated.

I don't like the idea of breaking people who expect dockershim default.. not without some deprecation timeline.

**Comment by saschagrunert** [comment]
Yes I agree, some pre-checks should be fine and some more verbose logging too.

**Comment by hickeyma** [comment]
Thanks for the feedback @mikebrow and @saschagrunert. I will look into this and push a PR shortly if that's ok?

**Comment by saschagrunert** [comment]
Sure, thanks for taking action @hickeyma :pray:

**Comment by hickeyma** [comment]
PR #599 pushed
