### ISSUE TITLE
Missing config set option

### ISSUE THREAD

**Issue by mikebrow** [kubernetes-sigs/cri-tools#602]
There's a config sub-command that's supposed to have get and set options ala git config pattern... the get works the set isn't there. 

```crictl config - Get and set crictl options```

**Comment by hickeyma** [comment]
@mikebrow I can work on this if thats ok?

**Comment by hickeyma** [comment]
Thanks @mikebrow. I will push a PR shortly.

**Comment by hickeyma** [comment]
@mikebrow The functionality is already there to set config from the cli. It is just not very user friendly.

I pushed PR #604 as a usability improvement. Please note in the PR description that it breaks CLI backwards compatibility. So, it might not be a suitable change.

**Comment by mikebrow** [comment]
> @mikebrow The functionality is already there to set config from the cli. It is just not very user friendly.
> 
> I pushed PR #604 as a usability improvement. Please note in the PR description that it breaks CLI backwards compatibility. So, it might not be a suitable change.

I see so the `--set` option was implemented in a silent fashion... or was the default for config if a field was provided...  hmm.. yeah that wasn't obvious

**Comment by hickeyma** [comment]
Yeah, not obvious. You called it without a flag as per this example:

```console
$ crictl config image-endpoint unix:///run/containerd/containerd.sock
```
