### ISSUE TITLE
config command overwrites config

### ISSUE THREAD

**Issue by mikebrow** [kubernetes-sigs/cri-tools#605]
What I expected to happen was to change only the runtime-endpoint in the config.

But what happened was it generated an entirely new config with defaults overwriting the prior config.
```
mike@mike-VirtualBox:~/go/src/k8s.io/kubernetes$ cat /etc/crictl.yaml
# important note: do not delete me
runtime-endpoint: unix:///run/containerd/containerd.sock

mike@mike-VirtualBox:~/go/src/k8s.io/kubernetes$ sudo crictl config runtime-endpoint unix:///run/crio/crio.sock

mike@mike-VirtualBox:~/go/src/k8s.io/kubernetes$ cat /etc/crictl.yaml
runtime-endpoint: unix:///run/crio/crio.sock
image-endpoint: ""
timeout: 0
debug: false
```

Suggest a --default for generating a new config, and modify current behavior to not delete comment lines blank lines other text in the config.

**Comment by mikebrow** [comment]
also.. zero timeout seems wrong

usage says the default should be 2s

**Comment by mikebrow** [comment]
looks like the func ReadConfig(filepath string) (*Config, error) { code in pkg/common/file.go is missing the default values for the config it creates.. probably need a newConfig func and pass that to ReadConfig... or something to that effect.

**Comment by mikebrow** [comment]
so two issues... when setting a config value the config command 
1) fails to generate a config struct with the correct defaults
2) overwrites the config file vs simply inserting new values, possibly resulting in loss of information

**Comment by hickeyma** [comment]
@mikebrow Pushed #606 as a fix for timeout issues.

**Comment by hickeyma** [comment]
@mikebrow I can work on PR for the writing only changes to file if that's ok?

**Comment by mikebrow** [comment]
Additional issue with config command:
```
mike@mike-VirtualBox:~/go/src/github.com/kubernetes-sigs/cri-tools$ sudo cat /etc/crictl.yaml
cat: /etc/crictl.yaml: No such file or directory
mike@mike-VirtualBox:~/go/src/github.com/kubernetes-sigs/cri-tools$ sudo crictl config
NAME:
   crictl config - Get and set crictl options.

The options are as follows:

- runtime-endpoint: Container runtime endpoint
- image-endpoint: Image endpoint
- timeout: Timeout of connecting to server
- debug: Enable debug output


USAGE:
   crictl config [command options] [<options>]

OPTIONS:
   --get value  show the option value
   --set value  set option (can specify multiple or separate values with commas: opt1=val1,opt2=val2)
   --help, -h   show help (default: false)
   
mike@mike-VirtualBox:~/go/src/github.com/kubernetes-sigs/cri-tools$ sudo cat /etc/crictl.yaml
null
```
Does an invalid write even if there are no config set items and still provides usage for the command.

**Comment by mikebrow** [comment]
so the remaining issue after #606 is merged is the invalid use and behavior of common config writer
