### ISSUE TITLE
crictl pods --name returns 0 exit code if no matches found

### ISSUE THREAD

**Issue by buccella** [kubernetes-sigs/cri-tools#609]
When searching for pods using the `--name` flag, `crictl pods` will always return a `0` exit code. This differs from other tools, such as grep, where an exit code of `1` is returned if no matches are found.

This behavior would be useful when scripting.

**Comment by saschagrunert** [comment]
Hey @buccella, :wave: I think we could add that behavior but I'm not sure if we would break existing scripts. We could add it as an option (`--exit-code`) like other tools implement it. Do you mind proposing a PR for that?

**Comment by buccella** [comment]
You're right, the existing behavior should probably be preserved. 

If I can find some time, I'll put together a PR.

**Comment by saschagrunert** [comment]
Sounds good, let me assign the issue to you
/assign @buccella

**Comment by saschagrunert** [comment]
Do you have any updates on this @buccella? :innocent: 

/remove-lifecycle stale
