### ISSUE TITLE
Are there crictl replacement for these dockerd commands

### ISSUE THREAD

**Issue by Sealteam56** [kubernetes-sigs/cri-tools#610]
- Ensure the host's network namespace is not shared:

    Need to find crictl replacement for this command:
    ```
    docker inspect --format 'NetworkMode={{ .HostConfig.NetworkMode }}'
    ```

- Ensure that the PIDs cgroup limit is used

    Need to replace this command.... 
    ```
    docker inspect ${container_id} --format '{{.HostConfig.PidsLimit }}' 
    ``` 
    with some `crictl inspect -o json` command. need to find the crictl analogue for docker's HostConfig.PidsLimit

**Comment by mikebrow** [comment]
crictl isn't a replacement for docker.... crictl relies on container runtimes to provide it's version of the `crictl inspect` result. Depending on the container runtime you are using, and the config.json used to run the container, there may or may not be sufficient detail in the inspect results to give you your answer.

**Comment by Sealteam56** [comment]
@mikebrow - thank you for your response. As you have mentioned crictl is not a replacement for dockerd cmds. My ask is if there is a crictl cmd like the docker inspect. I do believe that within Kubernetes there is now a solution.
