### ISSUE TITLE
suggest adding github actions

### ISSUE THREAD

**Issue by mikebrow** [kubernetes-sigs/cri-tools#613]
In particular it would be beneficial to be testing the various cloud container runtimes against cri-test against k8s master and cri-tools master to ensure stability of the CRI api. ATM only dockershim is being tested in travis for cri-tools CI.

Desired Actions:

- containerd items
  - [x] containerd master ubuntu 18.04 LTS runc 
  - [x] matrix over available platforms, releases of containerd, runtimes(crun, runc)

- crio items
  - [x] cri-o master ubuntu 18.04 LTS runc
  - [x] matrix over available platforms, releases of cri-o, runtimes(crun, runc)
  - [ ] remove SKIP for "runtime should support port mapping with host port and container port"

- dockershim items
  - [x] dockershim master ubuntu 18.04 LTS runc 
  - [ ] matrix over available platforms, releases of dockershim, runtimes(crun, runc), (Dockershim critest on Windows: wip #634)
  - [x] remove dockershim critest on travis, or fix it to run with a standalone dockershim, ...https://github.com/kubernetes-sigs/cri-tools/pull/611
  - [ ] need an owner/host for dockershim moby/kubernetes-sigs/_____ (not a scope fo cri-tools just tracking) (currently https://github.com/dims/cri-dockerd/pull/4)

- All Container Runtimes: 
  - [ ] missing platforms blocked by github action runners (linux-ppc64le, ARM, s390x, ...)
  - [ ] VM isolated pods / containers with runc/crun hosting inside a VM for each pod/container using katacontainers, (hyper(?) for windows)

**Comment by saschagrunert** [comment]
Okay, how would the test look like?

We test the `crictl` master against a stable version of container runtimes? We could also add prow jobs to test-infra for that. But I'm also open to use GitHub actions.

**Comment by mikebrow** [comment]
just a simple install and run of container runtime (with it's dependencies)
followed by running cri-test against it's sock..

I would suggest running against the latest release of the container runtime with a must run and the container runtime's master branch with an "optional" run.

**Comment by mikebrow** [comment]
https://github.com/containerd/cri/blob/master/.github/workflows/ci.yml#L75-L143

minus the unit and integration tests... and add a parameter to set the current master branch version of cri-tools .. I've been chatting it up a bit with @hickeyma for the potential of a containerd test here.. need to broach it with the cri-o team to add one for theirs.. similar to the e2e tests already added.  I like the github actions mostly because they can be tested in the developers fork before pushing the PR.

**Comment by saschagrunert** [comment]
Yeah, sounds good to me. :+1: Are you planning to open-up a PR for that?

**Comment by mikebrow** [comment]
> Yeah, sounds good to me. 👍 Are you planning to open-up a PR for that?

I or @hickeyma for containerd.. if that works out well we could do the crio one.. or someone could volunteer :-)

**Comment by mikebrow** [comment]
dockershim .. dunno..   I'd wait till it's back up working against k8s master again .. then maybe move it off travis as well..

**Comment by saschagrunert** [comment]
I can take the CRI-O part, for sure :)

**Comment by mikebrow** [comment]
> I can take the CRI-O part, for sure :)

I think you'll like github actions.

**Comment by hickeyma** [comment]
I can do the containerd part if that's ok?

**Comment by dims** [comment]
fyi, i got the standalone dockershim working in a github action
- https://github.com/dims/cri-tools/pull/3/files

Here's a clean run:
- https://github.com/dims/cri-tools/runs/717714970?check_suite_focus=true

**Comment by mikebrow** [comment]
> fyi, i got the standalone dockershim working in a github action
> 
> * https://github.com/dims/cri-tools/pull/3/files
> 
> Here's a clean run:
> 
> * https://github.com/dims/cri-tools/runs/717714970?check_suite_focus=true

Whoot! that's three CRIs!

**Comment by mikebrow** [comment]
now just need to decide where to put it..  kubernetes-sigs/dockershim?

**Comment by dims** [comment]
@mikebrow @thajeztah how about somewhere in moby github org?

**Comment by dims** [comment]
there was discussions already about this in code-organization and we did not like any of the options.

**Comment by hickeyma** [comment]
@dims Way to go. Excellent work. 👏

**Comment by dims** [comment]
fyi, i threw in a github action that uses cri-tool tests in the cri-dockerd repo and it turned out really well
latest run - https://github.com/dims/cri-dockerd/runs/720555441?check_suite_focus=true
github action itself - https://github.com/dims/cri-dockerd/blob/master/.github/workflows/main.yml

**Comment by hickeyma** [comment]
Nice work Dims! :)

**Comment by mikebrow** [comment]
added a work item list above

**Comment by saschagrunert** [comment]
Working on the CRI-O master part in https://github.com/kubernetes-sigs/cri-tools/pull/619

**Comment by saschagrunert** [comment]
> * [ ]  cri-o matrix over platforms, releases of containerd, runtimes(crun, runc, (kata?)

@mikebrow did you mean:

> * [ ]  cri-o matrix over platforms, releases of cri-o, runtimes(crun, runc, (kata?)

I guess we can add a test to run against the latest version of CRI-O. crun would be possible to if we add it to the static binary bundle of CRI-O.

**Comment by mikebrow** [comment]
> > * [ ]   cri-o matrix over platforms, releases of containerd, runtimes(crun, runc, (kata?)
> 
> @mikebrow did you mean:
> 
> > * [ ]   cri-o matrix over platforms, releases of cri-o, runtimes(crun, runc, (kata?)
> 
> I guess we can add a test to run against the latest version of CRI-O. crun would be possible to if we add it to the static binary bundle of CRI-O.

Yes, cri-o, cut and paste fail :-)

Really it just meant we should add appropriate test variations (possibly tagged as optional). 

For example, if you have a crio release candidate targeted to the latest release of kubernetes we should test that as well as your master. As for crun, I've been seeing subtle timing and other meta type issues with various tests when we switch from runc to crun. So probably good to run both possibly with crun as optional, so we can find those issues early with new or modified tests or dependencies (like :latest containers used in test).

**Comment by mikebrow** [comment]
updated status ^

**Comment by hickeyma** [comment]
@mikebrow I think the list could be updated following merging of PRs since last update. I would think all is complete except for:
- Owner for dockershim moby/kubernetes-sigs
- Dockershim critest on Windows: #634
- Build on linux-ppc64le: Not yet supported by GH actions

**Comment by mikebrow** [comment]
> @mikebrow I think the list could be updated following merging of PRs since last update. I would think all is complete except for:
> 
> * Owner for dockershim moby/kubernetes-sigs
> * Dockershim critest on Windows: #634
> * Build on linux-ppc64le: Not yet supported by GH actions

updated

**Comment by saschagrunert** [comment]
@mikebrow is there anything we would like to integrate before closing this issue? :)
