### ISSUE TITLE
crictl operation should be a separate package，not main

### ISSUE THREAD

**Issue by silenceper** [kubernetes-sigs/cri-tools#614]
Cri API (such as inspect, list, etc.) should be divided into separate packages, which can be called from outside

**Comment by saschagrunert** [comment]
Hey, @silenceper, may I ask you which benefits you see to split them up? cri-tools is usually not used as library which would support that use case, but I may be wrong.

**Comment by silenceper** [comment]
sorry,I found that grpc can be used to communicate with cri directly.

**Comment by saschagrunert** [comment]
Alright, feel free to open another issue if there is anything else unclear. :)
