### ISSUE TITLE
By default create (container) should not pull image

### ISSUE THREAD

**Issue by mikebrow** [kubernetes-sigs/cri-tools#625]
Details here:
https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images

Summary: kubernetes (kublet) manages pull policy for images.. and expects CRI to report status for images, pull images when requested (with and without auth), and create containers without doing the pull image.  

As such our default configuration/policy should be for create to just create container.. not pull image then create container.

Affects, performance, pre-loaded image scenarios, and disconnected scenarios.

**Comment by mikebrow** [comment]
Suggest a new config option to make --no-pull the default.

**Comment by saschagrunert** [comment]
Sounds good to me, are you going to submit a PR for that change?
