### ISSUE TITLE
Add Go 1.14 support

### ISSUE THREAD

**Issue by hickeyma** [kubernetes-sigs/cri-tools#639]
#### What would you like to be added:

Add Go 1.14 support to CI

#### Why is this needed:

Go 1.13 goes out of support before Kubernetes 1.19 release: https://github.com/kubernetes/kubernetes/pull/92438#issuecomment-651256619

#### Notes:

- There is a known issues with EINTR introduced in Go 1.14: https://golang.org/doc/go1.14#runtime
- This means for the Kubernetes ecosystem that there is a requirement for retrying syscall executions on receiving EINTR: https://github.com/kubernetes/kubernetes/pull/92438#issuecomment-650977961
- Therefore similar to Kubernetes and runc, will need to vendor on 1.13 and test on 1.13/1.14

**Comment by saschagrunert** [comment]
Yeah Kubernetes decided to skip go 1.14, we’re now thinking how to switch directly from 1.13 to 1.15. Do we wanna follow that approach, too?

**Comment by hickeyma** [comment]
That sounds good @saschagrunert, thanks. We could use this open issue to track the strategy when it becomes more apparent from Kubernetes side?

**Comment by saschagrunert** [comment]
There are still ongoing discussions about the path BF forward but I think a good tracking issue is https://github.com/kubernetes/release/issues/1216 for now. :)

**Comment by mikebrow** [comment]
yeah make 1.14 an optional top test..

**Comment by hickeyma** [comment]
@saschagrunert Thanks for pushing #651. Does the PR close this issue?

**Comment by saschagrunert** [comment]
I think so, yep
/close

**Comment by hickeyma** [comment]
That's great, thanks @saschagrunert
