### ISSUE TITLE
crictl inspect presents wrong args when health check are applied

### ISSUE THREAD

**Issue by snir911** [kubernetes-sigs/cri-tools#642]
#### What happened:

When you create a pod with health check and inspect its container using `crictl inspect` it presents "args:" as the health check args

(In the example below you get the "echo ..." cmd)

#### What you expected to happen:

`critctl inspect` should present the container args

(In the example below you would expect to get the "/bin/sh ..." cmd)

#### How to reproduce it (as minimally and precisely as possible):

1. Run some pod with health checks e.g. 

> apiVersion: v1
kind: Pod
metadata:
  name: insp
  labels:
spec:
  containers:
  \- name: insp
    image: fedora:latest
    args:
    \- /bin/sh
    \- \-c
    \- sleep infinity
    readinessProbe:
      exec:
        command:
        \- echo
        \- "test"
      initialDelaySeconds: 1
      periodSeconds: 1

2. get into the node running this pod
3. get the container id (`crictl ps`) and run:
`ctictl inspect <container id> | grep -A 5 args`

#### Anything else we need to know?:

* In the config.json file args are correct (while debug logs it's also incorrect)

#### Environment:

- Container runtime or hardware configuration:
  This happens with runc (with kata it worked correctly)

- OS (e.g: `cat /etc/os-release`):
NAME="Red Hat Enterprise Linux CoreOS"
VERSION="45.81.202006051300-0"
VERSION_ID="4.5"
OPENSHIFT_VERSION="4.5"
RHEL_VERSION="8.2"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 45.81.202006051300-0 (Ootpa)"

- Kernel (e.g. `uname -a`):
4.18.0-193.8.1.el8_2.x86_64

- Others:
crictl version 1.18.0

**Comment by saschagrunert** [comment]
Hey @snir911 :wave: may I ask you which container runtime you use on top of runc? Is it CRI-O, containerd or dockershim (integrated in Kubernetes)?

**Comment by saschagrunert** [comment]
I think this may be related to how the probes are implemented: Each probe will do an execsync request which (at least in CRI-O) overwrites the args passed to the container. This does not affect the state on disk and may be a bug (xref https://github.com/cri-o/cri-o/issues/3988).

**Comment by snir911** [comment]
This indeed was with with cri-o, thanks for the quick fix.

**Comment by saschagrunert** [comment]
Thank you for the report, let's track the issue in https://github.com/cri-o/cri-o/pull/3989

/close
