### ISSUE TITLE
critest against containerd under selinux fails 'runtime should support HostIpc is true'

### ISSUE THREAD

**Issue by dweomer** [kubernetes-sigs/cri-tools#650]
#### What happened:
With SELinux=Enforcing and updated `container-selinux` policy, `critest` is failing 'Security Context / NamespaceOption / **runtime should support HostIpc is true**'. I believe this is because of the fact that the container run for this assertion is not privileged (process label `container_t` instead of `spc_t`) which is needed to read host shared memory via `ipcs -m`.
See:
- https://github.com/containers/container-selinux/releases/tag/v2.143.0
- https://github.com/containerd/containerd/issues/4460

#### What you expected to happen:
`containerd` should pass `critest` with SELinux enforcing.

#### How to reproduce it (as minimally and precisely as possible):
- checkout https://github.com/containerd/containerd/pull/4451
- `export INSTALL_PACKAGES=https://github.com/dweomer/container-selinux/releases/download/v2.143.0/container-selinux-2.143.0-2.dev.gite2d5a9e.fc32.noarch.rpm`
- `vagrant up --provision-with=shell,selinux,test-cri`
- witness the single failure:
```
    default: Summarizing 1 Failure:
    default: 
    default: [Fail] [k8s.io] Security Context 
    default: NamespaceOption [It] runtime should support HostIpc is true 
    default: /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/security_context_linux.go:159
    default: 
    default: Ran 90 of 97 Specs in 68.387 seconds
    default: FAIL! -- 89 Passed | 1 Failed | 0 Pending | 7 Skipped
```
- `vagrant ssh  -c 'sudo ausearch -m avc -ts recent -c ipcs'`
```
----
time->Tue Aug 11 08:49:09 2020
type=AVC msg=audit(1597135749.972:7071): avc:  denied  { unix_read } for  pid=64429 comm="ipcs" key=-222557646  scontext=system_u:system_r:container_t:s0:c453,c1010 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=shm permissive=0
----
time->Tue Aug 11 08:49:09 2020
type=AVC msg=audit(1597135749.972:7072): avc:  denied  { unix_read } for  pid=64429 comm="ipcs" key=-227491983  scontext=system_u:system_r:container_t:s0:c453,c1010 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=shm permissive=0
----
time->Tue Aug 11 08:49:09 2020
type=AVC msg=audit(1597135749.972:7073): avc:  denied  { unix_read } for  pid=64429 comm="ipcs" key=1625385622  scontext=system_u:system_r:container_t:s0:c453,c1010 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=shm permissive=0
----
time->Tue Aug 11 08:49:09 2020
type=AVC msg=audit(1597135749.972:7074): avc:  denied  { unix_read } for  pid=64429 comm="ipcs" key=-528880287  scontext=system_u:system_r:container_t:s0:c453,c1010 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=shm permissive=0
----
time->Tue Aug 11 08:49:09 2020
type=AVC msg=audit(1597135749.972:7075): avc:  denied  { unix_read } for  pid=64429 comm="ipcs" key=1981708331  scontext=system_u:system_r:container_t:s0:c453,c1010 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=shm permissive=0
----
time->Tue Aug 11 08:49:09 2020
type=AVC msg=audit(1597135749.972:7076): avc:  denied  { unix_read } for  pid=64429 comm="ipcs" key=-1466713841  scontext=system_u:system_r:container_t:s0:c453,c1010 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=shm permissive=0
----
time->Tue Aug 11 08:49:09 2020
type=AVC msg=audit(1597135749.972:7077): avc:  denied  { unix_read } for  pid=64429 comm="ipcs" key=-2056816126  scontext=system_u:system_r:container_t:s0:c453,c1010 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=shm permissive=0
----
time->Tue Aug 11 08:49:09 2020
type=AVC msg=audit(1597135749.972:7078): avc:  denied  { unix_read } for  pid=64429 comm="ipcs" key=-63844995  scontext=system_u:system_r:container_t:s0:c453,c1010 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=shm permissive=0
```
#### Anything else we need to know?:
I am happy to work on a fix but wanted to submit the issue to elicit discussion beforehand.

#### Environment:

- Container runtime or hardware configuration:
  containerd 1.4.x (https://github.com/containerd/containerd/pull/4451)

- OS (e.g: `cat /etc/os-release`):
  Fedora 32

- Kernel (e.g. `uname -a`):
  `5.6.6-300.fc32.x86_64`

- Others:
  container-selinux from https://github.com/dweomer/container-selinux/releases/download/v2.143.0/container-selinux-2.143.0-2.dev.gite2d5a9e.fc32.noarch.rpm

**Comment by mikebrow** [comment]
In a nut.. the idea is container runtimes should nil the processLabel and mountLabel returned from selinux returned [InitLabels](https://github.com/containerd/cri/blob/56a89cda34644fedf0c99f96c888de5851e0e406/vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go#L30) when the pod-sandbox linux security policy is privileged, hostIPC, hostPID (what about hostNetwork?)....  Seems if that was supposed to be common behavior, we should document it (here)[https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces], and in the above InitLabels() call.

**Comment by mikebrow** [comment]
I surmise (from the crio code) container runtimes should nil (not use) the processLabel and mountLabel returned from selinux-InitLabels when the pod-sandbox linux security policy is privileged, or hostIPC, or hostPID (what about hostNetwork?).... Seems if that was supposed to be common behavior, we should document it (here)[https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces], and in the above InitLabels() call.
