### ISSUE TITLE
/usr/local/bin/crictl: 1: Syntax error: ")" unexpected

### ISSUE THREAD

**Issue by jeus** [kubernetes-sigs/cri-tools#660]
when install crictl for k3s with --docker and run "sudo crictl info" get this error: 
`/usr/local/bin/crictl: 1: Syntax error: ")" unexpected`

#### Environment:

- k3s-agent.service run with docker on ubuntu server for raspberry pi 4:
- OS (e.g: `20.04.1 LTS (Focal Fossa)`):
- Kernel (`Linux ingrow0 5.4.0-1016-raspi #17-Ubuntu SMP Wed Aug 19 14:54:44 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`):
- Others: I check all versions from 17.0 to 19 all of them return this error.

**Comment by saschagrunert** [comment]
Hey, thank you for opening the issue! :wave: 

> when install crictl for k3s with --docker and run "sudo crictl info" get this error:
> `/usr/local/bin/crictl: 1: Syntax error: ")" unexpected`

How did you install crictl? Might it be possible that `/usr/local/bin/crictl` is a wrapper? Whats the output of:

```
> file /usr/local/bin/crictl
```

**Comment by edigu** [comment]
For the others reading this thread investigating the issue:

I encountered the same while working on LF CKAD Lab and realized quite late that `crictl` was installed via provided lab bash scripts using `amd64` binary on an `arm64` machine (macOS) which ended up with the very same symptom:

```
/usr/local/bin/crictl: 1: Syntax error: ")" unexpected
```

So after using the proper arm64 distribution, it disappeared.
