### ISSUE TITLE
crictl inspecti does not print valid JSON when multiple image IDs provided

### ISSUE THREAD

**Issue by honnix** [kubernetes-sigs/cri-tools#669]
#### What happened:
I ran `crictl inspecti -o json <id1> <id2>`, and this output two JSON chunks instead of valid JSON array. The result makes using other tools to process output very hard.

#### What you expected to happen:
A valid JSON array containing two dictionaries.

#### How to reproduce it (as minimally and precisely as possible):
Run `crictl inspecti -o json <id1> <id2>` and examine the output.

#### Anything else we need to know?:
I guess the reason is that printing is done per image https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/image.go#L267, instead of composing a full JSON.

The same goes to YAML output as well.

So I think we can either output a complete JSON or have an option to output a single line json without pretty print. As for YAML, the only optional I think is to output multiple YAML doc separated by `---`

#### Environment:

- Container runtime or hardware configuration: Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel
- OS (e.g: `cat /etc/os-release`): [GKE containerd image](https://cloud.google.com/kubernetes-engine/docs/concepts/using-containerd)
- Kernel (e.g. `uname -a`): Linux <hostname> 4.19.112+ #1 SMP Fri Sep 4 12:00:04 PDT 2020 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
- Others:

**Comment by honnix** [comment]
A possible workaround could be replacing the output using regex `\}\s*\{` with `},{` and then padding `[]`. Still feels flaky though.

**Comment by saschagrunert** [comment]
Yeah, the same issue exists for `inspecti` and `inspectp`. The `for` loops are not taking the output type into account.

**Comment by honnix** [comment]
I feel this will hardly be prioritized. /close

**Comment by xiongtx** [comment]
I'm running into this issue as well. When querying 100's of images on a host it's more efficient to do one shell command than 100's.

**Comment by saschagrunert** [comment]
Approaching a fix in #1493
