### ISSUE TITLE
how to login my repository

### ISSUE THREAD

**Issue by lovebaby979** [kubernetes-sigs/cri-tools#671]
podman login my repository report error,how to setting?

error:
# podman login registry.my.com:31231
Authenticating with existing credentials...
Existing credentials are invalid, please enter valid username and password
Username (admin): admin
Password: 
Error: error authenticating creds for "registry.my.com:31231": pinging docker registry returned: Get https://registry.my.com:31231/v2/: http: server gave HTTP response to HTTPS client

**Comment by saschagrunert** [comment]
Hey @lovebaby979 can you please move that issue to Podman and go a bit more into detail by filling their issue template? This project is not really related to Podman.

**Comment by lovebaby979** [comment]
sorry,how to remove@saschagrunert

**Comment by saschagrunert** [comment]
Let's just close this for now.
/close
