### ISSUE TITLE
publish new rpm/deb releases

### ISSUE THREAD

**Issue by paulcostinean** [kubernetes-sigs/cri-tools#672]
RPMs for releases newer than 1.13 are not published (checked [stable](https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/filelists.xml) and [unstable](https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64-unstable/repodata/filelists.xml))

Related (closed) issue: https://github.com/kubernetes/release/issues/739

Posting this here to get more visibility.

**Comment by vrutkovs** [comment]
RPMs and DEBs are available at https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable:cri-o:1.21/cri-tools
