### ISSUE TITLE
how to attach a container?

### ISSUE THREAD

**Issue by axiqia** [kubernetes-sigs/cri-tools#675]
Hi, everyone, I run a container with a contianer.yaml :
```
metadata:
  name: ubuntu
image:
  image: ubuntu:16.04
command:
- sleep
args:
- 600
log_path: busybox.1.log
```

And the container is running in the background.
```
$ crictl ps -a
CONTAINER           IMAGE                                    CREATED             STATE               NAME                ATTEMPT             POD ID
f40910c338a68      ubuntu:16.04  18 seconds ago      Running             ubuntu-nydus        0                   d75a1a5972b74
```

Then I want to attach the running container but met a FATA.
```
$ sudo crictl attach -t=true f40910c338a68
FATA[0000] attaching running container failed: tty=true must be specified with interactive=true
```

**My question is how to attach a container?**

I also find an issue mentioned attach, [here](https://github.com/kubernetes-sigs/cri-tools/issues/433). If we use a command `bin/sh` in contianer.yaml, the container will be in  `Exited` state. And when attach from the command line, I met another FATA.
```
$ sudo crictl attach -t=true f40910c338a68
FATA[0000] attaching running container failed: rpc error: code = Unknown desc = container is in CONTAINER_EXITED state
```

Thank you.

**Comment by saschagrunert** [comment]
Can you try adding the `-i` flag for the `crictl attach` command, too?

**Comment by axiqia** [comment]
@saschagrunert  Thank you for your quick reply.  I try with `crictl attach -t=true -i=true containerID`, but there is no terminal, and I can not input anything. 
The command `crictl exec -i -t  containerID /bin/bash` provides an interactive input terminal for me. However, when the time specified in `continaer.yaml` runs out, the container exit. Is it possible to run a container and specify an interactive input terminal in `container.yaml`?
