### ISSUE TITLE
Unable to build from source tarball

### ISSUE THREAD

**Issue by dvzrv** [kubernetes-sigs/cri-tools#676]
#### What happened:

Hi! I would like to package cri-tools for Arch Linux. Unfortunately I am not able to build from a source tarball and therefore do a form of upstream source verification (via checksum comparison). From a packaging perspective this is not good.

#### What you expected to happen:
Download a release tarball (e.g. a CI manufactured tarball) and build from it after extracting it.

#### How to reproduce it (as minimally and precisely as possible):

```
make
fatal: not a git repository (or any of the parent directories): .git
```

However, critest is still being built:

```
CGO_ENABLED=0 GO111MODULE=on go test -mod=vendor -c -o /build/cri-tools/src/cri-tools-1.19.0/_output/critest \
        -ldflags '-X github.com/kubernetes-sigs/cri-tools/pkg/version.Version=' \
        -tags 'selinux' \
     github.com/kubernetes-sigs/cri-tools/cmd/critest
CGO_ENABLED=0 GO111MODULE=on go build -mod=vendor -o /build/cri-tools/src/cri-tools-1.19.0/_output/crictl \
        -ldflags '-X github.com/kubernetes-sigs/cri-tools/pkg/version.Version=' \
        -tags 'selinux' \
        github.com/kubernetes-sigs/cri-tools/cmd/crictl
```

#### Anything else we need to know?:
Without source (tarball) verification it is easier to fall for [supply chain attacks](https://en.wikipedia.org/wiki/Supply_chain_attack). 

On Arch Linux we are also able to use PGP signed tags for source verification. Note: The github provided PGP signatures are useless though, as they do not provide a chain of trust and do not identify a real person.

If you intend to provide detached PGP signatures for custom tarballs or signatures for your tags, please ensure to announce this (e.g. who is allowed to tag releases with which key) and make plans to ensure a [chain of trust](https://en.wikipedia.org/wiki/Chain_of_trust) in the future.

#### Environment:

- Container runtime or hardware configuration: n/a
- OS: Arch Linux
- Kernel (e.g. `uname -a`): Linux hmbx 5.8.16.a-1-hardened #1 SMP PREEMPT Sat, 17 Oct 2020 13:04:20 +0000 x86_64 GNU/Linux
- Others:
  - go: 1.15.3

**Comment by saschagrunert** [comment]
Hey @dvzrv, thank you for submitting the issue!

I think we could solve this problem with adding a dedicated VERSION file to the repository and reading the version from it instead of invoking a git command.

**Comment by dvzrv** [comment]
@saschagrunert is there any movement on this?

FWIW, I think auto-closing bots are really problematic, as they just hide these issues and they continue existing for a very long time....

**Comment by saschagrunert** [comment]
@dvzrv unfortunately not, we could either use a static version file or the build environment requires `git`. Both has pros and cons for sure.
