### ISSUE TITLE
Equivalent docker cp command

### ISSUE THREAD

**Issue by honnix** [kubernetes-sigs/cri-tools#677]
#### What would you like to be added:
`docker cp` similar command to sync files between a container and host file system.

#### Why is this needed:
Very often there is a need to copy files around. I couldn't find the equivalent command in `crictl`.

**Comment by saschagrunert** [comment]
Hey @honnix. thank you for the feature request. Unfortunately the Container Runtime Interface (CRI) does not support that functionality. `crictl` only implements this interface and kinda mimics partly the kubelet's interface. I think sticking to `kubectl cp` might be the best alternative here.

**Comment by honnix** [comment]
@saschagrunert Thanks for explaining! Yeah that is indeed the best alternative, although the limitation of `kubectl cp` is annoying for certain cases.

**Comment by CharlyRipp** [comment]
Looking to debug a connectivity issue in a container built on `scratch` by copying in a shell. Issue with `kubectl cp` is it utilizes `tar`, which is also not present :)

Figured I'd see if there was any ideas here as it's the place I keep landing back on.

**Comment by Ahmad-Faizan** [comment]
@CharlyRipp did you find an alternative way to copy files without using `kubectl cp` ?
I am trying to copy a file to a distroless container which is missing `tar`, `vi`, `sed` and most other tools.
I only have `cat`, `tee` and `echo`.
