### ISSUE TITLE
container or pod config.json examples

### ISSUE THREAD

**Issue by perezjasonr** [kubernetes-sigs/cri-tools#709]
#### What would you like to be added:

a reference in the docs on the container-config.json/yaml and pod-config.json/yaml

#### Why is this needed:

the example in the docs only has about 4 entries, i could not find a reference that shows the entire spec of options like if I want to mount fs and such (if applicable). or if its based on something external maybe a link to their reference?

this is the only example we can go off of:

```
{
    "metadata": {
        "name": "nginx-sandbox",
        "namespace": "default",
        "attempt": 1,
        "uid": "hdishd83djaidwnduwk28bcsb"
    },
    "log_directory": "/tmp",
    "linux": {
    }
}
```

or if this is in the docs somewhere I am having trouble finding it.

**Comment by perezjasonr** [comment]
also if volume mounts are not an option here at all and not intended letting me know would save the trouble.
but I still think an example with the full range of options in the specs would be useful (unless the examples in the docs are)

**Comment by dalehamel** [comment]
@perezjasonr I too was surprised the examples were such stubs. Walking through the code, it lead me to this struct:

https://github.com/kubernetes-sigs/cri-tools/blob/eae503c01c469500a468f2ab5f628463584b8b58/vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go#L3235

Which i guess constitutes the only "documentation" in term of what fields may be valid as far as I can tell.

**Comment by perezjasonr** [comment]
> @perezjasonr I too was surprised the examples were such stubs. Walking through the code, it lead me to this struct:
> 
> https://github.com/kubernetes-sigs/cri-tools/blob/eae503c01c469500a468f2ab5f628463584b8b58/vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go#L3235
> 
> Which i guess constitutes the only "documentation" in term of what fields may be valid as far as I can tell.

thats a nice find, I guess thats what we got if were desperate for now
