### ISSUE TITLE
Provide .sha256 files in release artifiacts

### ISSUE THREAD

**Issue by micahhausler** [kubernetes-sigs/cri-tools#716]
#### What would you like to be added:

#322 and #323 addressed producing .sha256 output to the release text, but I'd like `<filename>.sha256` files produced as well.

#### Why is this needed:

It'd be helpful to be able to programmatically fetch the shasums of artifacts so separate build processes that verify the integrity of the download. I'm working on kubernetes-sigs/kind#2033 and would like to fetch these programmatically.

**Comment by saschagrunert** [comment]
I agree this seems useful. :+1:

**Comment by MaXinjian** [comment]
Seems now still no .sha256 files  in release artifiacts.  [Modify hack/release.sh script to include sha256 sum files #717] (https://github.com/kubernetes-sigs/cri-tools/pull/717) only show sha256 context
