### ISSUE TITLE
`--image-endpoint` does not use `--runtime-endpoint` as documented in crictl usage

### ISSUE THREAD

**Issue by maybe-sybr** [kubernetes-sigs/cri-tools#722]
#### What happened:
Setting `--runtime-endpoint` or `$CONTAINER_RUNTIME_ENDPOINT` does not appear to set the image endpoint to the same value as suggested in the usage text:

>    --image-endpoint value, -i value    Endpoint of CRI image manager service (default: uses 'runtime-endpoint' setting) [$IMAGE_SERVICE_ENDPOINT]

#### What you expected to happen:
I should be able to set `--runtime-endpoint` and not bother with `--image-endpoint`

#### How to reproduce it (as minimally and precisely as possible):
```
[maybe@karma cri-o]$ crictl images
FATA[0002] connect: connect endpoint 'unix:///var/run/crio/crio.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded
[maybe@karma cri-o]$ crictl --runtime-endpoint unix:///run/user/1337/usernetes/crio/crio.sock images
FATA[0002] connect: connect endpoint 'unix:///var/run/crio/crio.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded
[maybe@karma cri-o]$ CONTAINER_RUNTIME_ENDPOINT=unix:///run/user/1337/usernetes/crio/crio.sock crictl images
FATA[0002] connect: connect endpoint 'unix:///var/run/crio/crio.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded
[maybe@karma cri-o]$ crictl --image-endpoint unix:///run/user/1337/usernetes/crio/crio.sock images
IMAGE                       TAG                 IMAGE ID            SIZE
docker.io/library/busybox   1.31.0              19485c79a9bbd       1.44MB
k8s.gcr.io/pause            3.2                 80d28bedfe5de       688kB
[maybe@karma cri-o]$ IMAGE_SERVICE_ENDPOINT=unix:///run/user/1337/usernetes/crio/crio.sock crictl images
IMAGE                       TAG                 IMAGE ID            SIZE
docker.io/library/busybox   1.31.0              19485c79a9bbd       1.44MB
k8s.gcr.io/pause            3.2                 80d28bedfe5de       688kB
```

#### Environment:

- Container runtime or hardware configuration: CRI-O 1.20.0 (d388528dbed26b93c5bc1c89623607a1e597aa57)
- OS (e.g: `cat /etc/os-release`): Fedora 33
- Kernel (e.g. `uname -a`): 5.10.15-200.fc33
- Others:

**Comment by povsister** [comment]
This probably caused by incorrect `ImageEndpoint` set in `crictl.yaml`.
If you have `ImageEndpoint` set in config yaml, and you only overrides the `RuntimeEndpoint` with CLI flags, the `ImageEndpoint` will not automatically changed to `RuntimeEndpoint` as you already have it explicitly defined in config yaml.

Check your crictl.yaml at `/etc/crictl.yaml`
