### ISSUE TITLE
FATA[0000] getting the runtime version: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Ruilkyu** [kubernetes-sigs/cri-tools#727]
FATA[0000] getting the runtime version: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR

**Comment by saschagrunert** [comment]
Hey @Ruilkyu, may I ask you to share more information about this issue? To which server (container runtime) are you trying to connect? Which crictl version are you using?

**Comment by Ruilkyu** [comment]
I used crictl 1.20

**Comment by saschagrunert** [comment]
Alright. But did you use containrs? This does not support the crictl right now.

**Comment by Ruilkyu** [comment]
When will it be possible？

**Comment by Ruilkyu** [comment]
I have solved it.

**Comment by saschagrunert** [comment]
> I have solved it.

How did you do that?

**Comment by saschagrunert** [comment]
Closing because the issue seems solved
