### ISSUE TITLE
CI fails with Failed to start crio.service: Unit crio.service not found.

### ISSUE THREAD

**Issue by vorburger** [kubernetes-sigs/cri-tools#729]
My #718 has _[Some checks were not successful](https://github.com/kubernetes-sigs/cri-tools/pull/718/checks?check_run_id=2107410132)_ but it's unrelated to that (trivial) change, and I've rebased to the latest `master` branch:

```
Run sudo mkdir -p /etc/crio/crio.conf.d
[crio.runtime]
log_level = "debug"
Failed to start crio.service: Unit crio.service not found.
Error: Process completed with exit code 5.
```

**Comment by saschagrunert** [comment]
Thank you for the report @vorburger, a fix is in flight: https://github.com/kubernetes-sigs/cri-tools/pull/730
