### ISSUE TITLE
Crictl pull images from 'registry.connect.redhat.com' with '--creds' failed

### ISSUE THREAD

**Issue by yimin-zhao** [kubernetes-sigs/cri-tools#731]
#### What happened:
```
# crictl pull registry.connect.redhat.com/hazelcast/hazelcast-3-rhel7:3.11 --creds <myusername>[:<mypassword>]
FATA[0001] pulling image: rpc error: code = Unknown desc = unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
```

#### What you expected to happen:
Pull images from 'registry.connect.redhat.com'
#### Anything else we need to know?:
I can use the same username/password to login docker, podman and skopeo.
I also tried `--auth AUTH_STRING` and got the same result.
#### Environment:

- Container runtime or hardware configuration: crio version 1.21.0-dev
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.9.2009 (Core)
- Kernel (e.g. `uname -a`): 4.20.17
- Others:

**Comment by feiskyer** [comment]
@saschagrunert  any ideas on this?

**Comment by saschagrunert** [comment]
Hey @yimin-zhao, unfortunately I cannot reproduce the issue with the latest CRI-O v1.20.1. What I did:

1. Created a service account like described there:
  https://catalog.redhat.com/software/containers/hazelcast/hazelcast-3-rhel7/5ae31e6129373854f0bba061?container-tabs=gti&gti-tabs=registry-tokens
2. sudo crictl pull --creds 'username:token' registry.connect.redhat.com/hazelcast/hazelcast-3-rhel7

Which kind of credentials are you using? May it be possible that they're not valid for the registry?

**Comment by yimin-zhao** [comment]
Hi, I followed your link, but got the same error.

Anyway, thanks for the reply, so far I use skopeo as a workaround. Since I am using a development branch of crio/cri-tools, if it's not reproducible, I will close this later today.

**Comment by saschagrunert** [comment]
> Anyway, thanks for the reply, so far I use skopeo as a workaround. Since I am using a development branch of crio/cri-tools, if it's not reproducible, I will close this later today.

Thank you for the update, feel free to reach out anytime if the issue is reproducible for you! :pray:
