### ISSUE TITLE
Unable to list containers

### ISSUE THREAD

**Issue by simar7** [kubernetes-sigs/cri-tools#758]
Hi thanks for maintaining this repo, I'm just having some difficulty getting started so below is my report:

#### What happened:

`crictl ps -a` doesn't list any containers.

#### What you expected to happen:

`crictl ps -a` should list all containers.

#### How to reproduce it (as minimally and precisely as possible):
```
vagrant@ubuntu-groovy:/usr/vagrant/repos/cri-testing-2$ sudo crictl ps
DEBU[0000] get runtime connection                       
DEBU[0000] connect using endpoint 'unix:///run/containerd/containerd.sock' with '2s' timeout 
DEBU[0000] connected successfully using endpoint: unix:///run/containerd/containerd.sock 
DEBU[0000] get image connection                         
DEBU[0000] connect using endpoint 'unix:///run/containerd/containerd.sock' with '2s' timeout 
DEBU[0000] connected successfully using endpoint: unix:///run/containerd/containerd.sock 
DEBU[0000] ListContainerRequest: &ListContainersRequest{Filter:&ContainerFilter{Id:,State:&ContainerStateValue{State:CONTAINER_RUNNING,},PodSandboxId:,LabelSelector:map[string]string{},},} 
DEBU[0000] ListContainerResponse: &ListContainersResponse{Containers:[]*Container{},} 
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID
vagrant@ubuntu-groovy:/usr/vagrant/repos/cri-testing-2$ sudo ctr c ls
CONTAINER    IMAGE                             RUNTIME                  
nginx        docker.io/library/nginx:latest    io.containerd.runc.v2    
nginx-2      docker.io/library/nginx:latest    io.containerd.runc.v2   
```

#### Anything else we need to know?:

Containers are running and present as it can be seen with the `ctr` tool output.
```
vagrant@ubuntu-groovy:/usr/vagrant/repos/cri-testing-2$ sudo ctr c ls
CONTAINER    IMAGE                             RUNTIME                  
nginx        docker.io/library/nginx:latest    io.containerd.runc.v2    
nginx-2      docker.io/library/nginx:latest    io.containerd.runc.v2   
```

I have also tried to use the cri-api library bindings. Below is minimal program:
```
package main

import (
	"context"
	"fmt"
	"log"

	"google.golang.org/grpc"
	pb "k8s.io/cri-api/pkg/apis/runtime/v1alpha2"
)

const addr = "unix:///run/containerd/containerd.sock"

func main() {
	conn, err := grpc.Dial(addr, grpc.WithInsecure())
	if err != nil {
		log.Fatal(err)
	}

	runtimeClient := pb.NewRuntimeServiceClient(conn)
	r, err := runtimeClient.ListContainers(context.Background(), &pb.ListContainersRequest{})
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Listing containers...")
	for _, ctr := range r.GetContainers() {
		fmt.Println(ctr.Id, ctr.Image, ctr.CreatedAt, ctr.State)
	}
}
```
Prints no running containers.

#### Environment:

- Container runtime or hardware configuration: containerd, running in a vagrant box with virtualbox provider.
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.10
- Kernel (e.g. `uname -a`): Linux ubuntu-groovy 5.8.0-50-generic #56-Ubuntu SMP Mon Apr 12 17:18:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by feiskyer** [comment]
are those containers created via cri interface?

**Comment by simar7** [comment]
> are those containers created via cri interface?

They are created with ctr tool. Is creating them through the CRI interface a pre requisite? 

If so, how would it work with the current version of Docker? And cri-o?

**Comment by feiskyer** [comment]
tag @mikebrow for containerd behavior on this API.

**Comment by simar7** [comment]
I see. It's similar behaviour with docker as well. I just want to know if CRI API is able to pick those up (containers created manually by containerd or docker cli) or if they have to be created with `crictl`?

We're looking to leverage CRI api as a way to be able to list running containers as it is runtime agnostic. That's the original motivation for this issue.

**Comment by simar7** [comment]
Looks like this was an error on my part. I was using `minikube` which spins up a VM and I was using the `crictl` tool outside of the VM. Shelling into the VM with `minikube ssh` and running `crictl` worked fine. Sorry about the noise.
