### ISSUE TITLE
Use crictl pull private register image,Failed to pull image rpc error: code = Unknown

### ISSUE THREAD

**Issue by Mrzhangxd** [kubernetes-sigs/cri-tools#760]
#### What happened:
I use crictl pull a private register image，can't pull success. the error log is "Failed to pull image "registry.mgzf.com/devops/jenkins:lts": rpc error: code = Unknown desc = failed to pull and unpack image "registry.xxx.com/devops/jenkins:lts": failed to resolve reference "registry.xxx.com/devops/jenkins:lts": unexpected EOF"

![error](https://user-images.githubusercontent.com/16274179/116370633-29a3bc80-a83d-11eb-88ae-b49fffa4b959.png)
I have modified the configuration file of containerd 
![containerd config](https://user-images.githubusercontent.com/16274179/116370261-cca80680-a83c-11eb-87c8-159f54790034.png)

but I use ctr nerdctl or docker pull images ok。

![success](https://user-images.githubusercontent.com/16274179/116370949-7e473780-a83d-11eb-8320-f3447e1e7ce5.png)

#### What you expected to happen:
Can successfully pull the private image 
#### Environment:

- Container runtime or hardware configuration:
 - containerd v1.4.3
- OS (e.g: `cat /etc/os-release`):
  - CentOS Linux release 8.3.2011
- Kernel (e.g. `uname -a`):
  - Linux master-03 5.11.0-1.el8.elrepo.x86_64
- Others:

**Comment by saschagrunert** [comment]
This looks like containerd related, @mikebrow may you give this one a look?

**Comment by mikebrow** [comment]
ctr and nerdctl don't use the CRI config... But let's close this here as it is not an issue with crictl... You can take a look at the issues/discussions over on containerd/containerd regarding registry support, the docs in containerd/containerd/docs/cri/* and the changes coming to the latest containerd configuration for registry mirrors, auth, etc..
