### ISSUE TITLE
crictl rm -f   when container is running only stops container not stop and remove

### ISSUE THREAD

**Issue by furman-d1** [kubernetes-sigs/cri-tools#780]
#### What happened: 
Issued **crictl rm -f containerID** while the container was still running

#### What you expected to happen: 
Expected to see container stopped and removed

#### How to reproduce it (as minimally and precisely as possible): 
start a container that sleeps forever.  issue crictl rm -f on that container

#### Anything else we need to know?:  
I debugged the problem - easy fix.  
In container.go located in the crictl directory, need to remove the _continue_ statement on line 357

                          if resp.GetStatus().GetState() == pb.ContainerState_CONTAINER_RUNNING {
      
        				if ctx.Bool("force") {
        					if err := StopContainer(runtimeClient, id, 0); err != nil {
        						logrus.Errorf("stopping the container %q failed: %v", id, err)
        						errored = true
        						continue 
        					}
     
        					continue   <<---- remove this code so we can fall through to the actual remove
      
        				} else {
        					logrus.Errorf("container %q is running, please stop it first", id)
        					errored = true
         					continue
        				}   
             			}
                               err = RemoveContainer(runtimeClient, id)

**Comment by saschagrunert** [comment]
Hey @furman-d1, that's a good catch! Especially since the removal of a container (without force) works as intended. I think we should fix that behavior. Do you wanna open a PR for that?

**Comment by furman-d1** [comment]
Sure, I'll do a PR.
