### ISSUE TITLE
crictl image tag and image push support

### ISSUE THREAD

**Issue by mraghu4** [kubernetes-sigs/cri-tools#793]
#### What would you like to be added:
crictl to support image tag and push.
#### Why is this needed:
Since docker is not a industry standard anymore, we want move away from that completely.

**Comment by saschagrunert** [comment]
Hey @mraghu4 thank you for opening the issue. Right now `crictl` follows the CRI (Kubernetes) implementation which does not support this functionality.

**Comment by mraghu4** [comment]
does crictl is not part containerd project? it says image push is in scope for containerd. Am I misunderstanding something here?
https://github.com/containerd/containerd/blob/main/SCOPE.md

**Comment by saschagrunert** [comment]
@mraghu4 no, this is an independent project. It more belongs to Kubernetes (SIG Node) rather than a specific container runtime. :)

**Comment by offSwitch** [comment]
you can use 
ctr --namespace=k8s.io image tag docker.io/library/httpd:latest k8s.gcr.io/httpd:latest
or
nerdctl -n k8s.io tag docker.io/library/httpd:latest k8s.gcr.io/httpd:latest

**Comment by NotArthur** [comment]
> > Vous pouvez utiliser la commande ctr --namespace=k8s.io Image Tag docker.io/library/httpd:latest k8s.gcr.io/httpd:latest ou nerdctl -n k8s.io tag docker.io/library/httpd:latest k8s.gcr.io/httpd:latest
> 
> namespace Je comprends, je vais essayer. Les miroirs hébergés en Chine ne fonctionnent pas, je suis à bout. v1.26
