### ISSUE TITLE
crictl image pull is not loading global cert until containerd restarted

### ISSUE THREAD

**Issue by mraghu4** [kubernetes-sigs/cri-tools#800]
After adding a certificate for private registry in global trust list and update-ca-certs command, any tool in the linux must able to use that cert for validation. ctr tool which comes with containerd able to pull image after update-ca-certs. but crictl showing error that the CA is unauthorized. 

#### What happened:
crictl pull giving "certificate signed by unknown authority"

#### What you expected to happen:
crictl pull should work 

#### How to reproduce it (as minimally and precisely as possible):
- create a private registry with self-signed certs and add a image
- add certs to global trust list and do update-ca-certs in node where crictl pull is being perfomed
- do crictl pull for image in private registry

#### Anything else we need to know?:
ctr tool able to pull image but only crictl is not, until containerd restarted.
#### Environment:
we tested in SUSE linux.

- Container runtime or hardware configuration: 
     - containerd version : 1.4.4
     - crictl version 1.21.0

**Comment by feiskyer** [comment]
it looks like a containerd issue. @mikebrow could you help to confirm?

**Comment by mikebrow** [comment]
Confirmed this issue should be closed and reopened in github.com/containerd/containerd
