### ISSUE TITLE
Differences in output between docker and crictl commands

### ISSUE THREAD

**Issue by Sungjun-Ohh** [kubernetes-sigs/cri-tools#824]
Where I work, the container engine or platform is different for each department.
I found that crictl supports docker, containerd, cri-o.
So from the security department's point of view, I think this project is attractive and worthwhile.
This is because I can use crictl to check whether the container is abnormal, regardless of which container engine is running on the machine.

However, the result of crictl is a bit strange.
For example, docker ps - crictl ps results in different values.

How should I interpret this?

# docker ps

> CONTAINER ID   IMAGE                         COMMAND                  CREATED      STATUS      PORTS     NAMES
ad5ce6c8105e   7aa1277761b5                  "start_runit"            2 days ago   Up 2 days             k8s_calico-node_calico-node-vg22g_kube-system_56d88435-f6f8-4718-96ab-a7debbfc3c74_1
6e0b3ecacbee   2c25d0f89db7                  "kube-controller-man…"   2 days ago   Up 2 days             k8s_kube-controller-manager_kube-controller-manager-k8s001_kube-system_af68639ce8a71342a589dd68ed2ee3ef_2
381435b14b45   078b6f04135f                  "/cluster-proportion…"   2 days ago   Up 2 days             k8s_autoscaler_dns-autoscaler-7df78bfcfb-7wt2j_kube-system_c2ab7f16-b769-4974-aa0b-9426bba0cf35_1
dd992fdc0f07   296a6d5035e2                  "/coredns -conf /etc…"   2 days ago   Up 2 days             k8s_coredns_coredns-8474476ff8-6crkv_kube-system_655006a6-7837-45fa-8bf6-209633db0c3f_1
489c2bc93fbe   k8s.gcr.io/pause:3.3          "/pause"                 2 days ago   Up 2 days             k8s_POD_dns-autoscaler-7df78bfcfb-7wt2j_kube-system_c2ab7f16-b769-4974-aa0b-9426bba0cf35_1
518c65e1f6c7   k8s.gcr.io/pause:3.3          "/pause"                 2 days ago   Up 2 days             k8s_POD_coredns-8474476ff8-6crkv_kube-system_655006a6-7837-45fa-8bf6-209633db0c3f_1
8de502ce303e   ef4bce0a7569                  "/usr/local/bin/kube…"   2 days ago   Up 2 days             k8s_kube-proxy_kube-proxy-mt6hl_kube-system_31506246-e8d7-47ab-885c-b1e2386aba80_1
36be32b9a8fe   cef7457710b1                  "kube-apiserver --ad…"   2 days ago   Up 2 days             k8s_kube-apiserver_kube-apiserver-k8s001_kube-system_fa6a94391d9103ffd4067665ad48306e_2
42a3c6448054   993d3ec13feb                  "kube-scheduler --au…"   2 days ago   Up 2 days             k8s_kube-scheduler_kube-scheduler-k8s001_kube-system_0df139f73995a58f51eccaa4c4ad7fcb_1
6b8dda5c2709   21fc69048bd5                  "/node-cache -locali…"   2 days ago   Up 2 days             k8s_node-cache_nodelocaldns-xrbvz_kube-system_4ab7c77f-ffea-4fb9-96b0-2612a4277cd7_1
7da0ea861214   k8s.gcr.io/pause:3.3          "/pause"                 2 days ago   Up 2 days             k8s_POD_calico-node-vg22g_kube-system_56d88435-f6f8-4718-96ab-a7debbfc3c74_2
ce20df33836c   k8s.gcr.io/pause:3.3          "/pause"                 2 days ago   Up 2 days             k8s_POD_kube-controller-manager-k8s001_kube-system_af68639ce8a71342a589dd68ed2ee3ef_2
d5890eef1533   k8s.gcr.io/pause:3.3          "/pause"                 2 days ago   Up 2 days             k8s_POD_kube-apiserver-k8s001_kube-system_fa6a94391d9103ffd4067665ad48306e_2
c1ee72e5d6e0   k8s.gcr.io/pause:3.3          "/pause"                 2 days ago   Up 2 days             k8s_POD_kube-scheduler-k8s001_kube-system_0df139f73995a58f51eccaa4c4ad7fcb_1
9d3d3f0e1a8a   k8s.gcr.io/pause:3.3          "/pause"                 2 days ago   Up 2 days             k8s_POD_kube-proxy-mt6hl_kube-system_31506246-e8d7-47ab-885c-b1e2386aba80_1
e791f07731be   k8s.gcr.io/pause:3.3          "/pause"                 2 days ago   Up 2 days             k8s_POD_nodelocaldns-xrbvz_kube-system_4ab7c77f-ffea-4fb9-96b0-2612a4277cd7_1
e695d9cffcea   quay.io/coreos/etcd:v3.4.13   "/usr/local/bin/etcd"    2 days ago   Up 2 days             k8s001

# crictl ps
> CONTAINER           IMAGE               CREATED             STATE               NAME                      ATTEMPT             POD ID
ad5ce6c8105ee       7aa1277761b51       2 days ago          Running             calico-node               1                   7da0ea8612148
6e0b3ecacbee9       2c25d0f89db7a       2 days ago          Running             kube-controller-manager   2                   ce20df33836cb
381435b14b456       078b6f04135ff       2 days ago          Running             autoscaler                1                   489c2bc93fbe6
dd992fdc0f075       296a6d5035e2d       2 days ago          Running             coredns                   1                   518c65e1f6c73
8de502ce303ed       ef4bce0a7569b       2 days ago          Running             kube-proxy                1                   9d3d3f0e1a8a8
36be32b9a8fe5       cef7457710b1a       2 days ago          Running             kube-apiserver            2                   d5890eef1533e
42a3c64480541       993d3ec13feb2       2 days ago          Running             kube-scheduler            1                   c1ee72e5d6e02
6b8dda5c27099       21fc69048bd5d       2 days ago          Running             node-cache                1                   e791f07731be8

How should I interpret this?

## environment
# cat /etc/crictl.yaml
runtime-endpoint: unix:///var/run/dockershim.sock
image-endpoint: unix:///var/run/dockershim.sock
timeout: 30
debug: false

# crictl version
Version:  0.1.0
RuntimeName:  docker
RuntimeVersion:  20.10.8
RuntimeApiVersion:  1.41.0

# crictl -version
crictl version v1.22.0

# docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:49 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:54:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

# uname -a
Linux k8s001 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by afbjorklund** [comment]
There are lots of differences between the output from the tools, for instance names and sizes vary greatly.
