### ISSUE TITLE
Cri-tools remote connection over tcp on Unix systems

### ISSUE THREAD

**Issue by loyaxa** [kubernetes-sigs/cri-tools#846]
Hello. I want to connect to remote Containerd with CRI-Plugin host. 
I configured **/etc/containerd/config.toml** to enable cri remote with:
```
[plugins."io.containerd.grpc.v1.cri"]

  # disable_tcp_service disables serving CRI on the TCP server.
  # Note that a TCP server is enabled for containerd if TCPAddress is set in section [grpc].
  disable_tcp_service = false

  # stream_server_address is the ip address streaming server is listening on.
  stream_server_address = "0.0.0.0"

  # stream_server_port is the port streaming server is listening on.
  stream_server_port = "0"
```

I detect, that I can connect to CRI Plugin from Windows system and  I can execute any commands. But when I try to connect from Linux system i got error: **"connect: only support unix socket endpoint"**. I rewrite **k8s.io/kubernetes/pkg/kubelet/cri/util_unix** to support TCP like on util_windows with:
```
const (
	// unixProtocol is the network protocol of unix socket.
	unixProtocol = "unix"
	tcpProtocol   = "tcp"
)

func GetAddressAndDialer(endpoint string) (string, func(ctx context.Context, addr string) (net.Conn, error), error) {
	protocol, addr, err := parseEndpoint(endpoint)
	if err != nil {
		return "", nil, err
	}

	if protocol == tcpProtocol {
		return addr, tcpDial, nil
	}

	if protocol == unixProtocol {
		return addr, dial, nil
	}

	return "", nil, fmt.Errorf("only support tcp and unix endpoint")
}
```
Its worked.

Why did you not add support of **TCP** socket for crictl clients on Unix systems? Will you do this later?

**Comment by simonhoss** [comment]
Hey @loyaxa 

Sorry for the off-topic questions, but I hope you can help me.

How did you manage to remote connect? For me it doesn't work, also not over windows.

This is what I try:

```
crictl.exe -D -r tcp://192.168.1.156 info

time="2022-03-18T22:56:14+01:00" level=debug msg="get runtime connection"
time="2022-03-18T22:56:14+01:00" level=debug msg="connect using endpoint 'tcp://192.168.1.156:58188' with '2s' timeout"
time="2022-03-18T22:56:16+01:00" level=fatal msg="connect: connect endpoint 'tcp://192.168.1.156:58188', make sure you are running as root and the endpoint has been started: context deadline exceeded"
```

I tried also with the generated port `crictl.exe -D -r tcp://192.168.1.156:58188 info`

My config for ContainerD looks same like yours. If you could help I would appreciate it a lot! ContainerD is also running on windows.
