### ISSUE TITLE
Do not show the image with tag none

### ISSUE THREAD

**Issue by offSwitch** [kubernetes-sigs/cri-tools#850]
#### What would you like to be added:
![image](https://user-images.githubusercontent.com/11695496/142973660-3c85945d-c77f-4186-a889-51f913ec65ca.png)
Do not show the image with tag none
#### Why is this needed:
Cannot be deleted and makes no sense

**Comment by saschagrunert** [comment]
Hey @offSwitch the images with no tag could be directly removed by using their image ID.

**Comment by offSwitch** [comment]
> Hey @offSwitch the images with no tag could be directly removed by using their image ID.

This way I will delete all the images, but I only want to delete the images with tag none
