### ISSUE TITLE
Release v1.23.0

### ISSUE THREAD

**Issue by thiguetta** [kubernetes-sigs/cri-tools#856]
#### What would you like to be added:
k8s 1.23 was released on Dec 7th and still we don't have a cri-tools release for 1.23

**Comment by saschagrunert** [comment]
I'd like to get the CI back before doing a release. Right now there seems to be two in flight:
- https://github.com/kubernetes-sigs/cri-tools/pull/858
- https://github.com/kubernetes-sigs/cri-tools/pull/853

We're not in a hurry since we would be still backwards compatible with Kubernetes. We also do not have CRI v1 support merged yet, so the changes between 1.22 and 1.23 seem marginal.

**Comment by saschagrunert** [comment]
@feiskyer @mrunalp do we wanna switch to CRI v1 before releasing 1.23? This would be a breaking change.

Or do we wanna support both CRI versions in parallel? We could make it configurable, but it would increase the implementation effort.

**Comment by hswong3i** [comment]
With Kubernetes usual N / N-1 support style, shall critool 1.23 support both Kubernetes 1.23 / 1.22?

If yes, does OCI only supported by Kubernetes 1.22, or still required for legacy Docker format support?

**Comment by afbjorklund** [comment]
The packages are still on 1.19, so I think `crictl` has a longer life span.

The [homepage](https://github.com/kubernetes-sigs/cri-tools#current-status) says that it supports anything from k8s 1.16.x and up

**Comment by afbjorklund** [comment]
If you use cri-o, it sets up 1.21 to be used.

```
 cri-tools |   1.21.0~2 | http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Packages
```

If you use containerd, you get 1.19 instead

```
 cri-tools |  1.19.0-00 | https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
```

----

Assuming that one wants to use modern packaging, like apt.

And not fall back to having to install odd things from tarballs.

**Comment by hswong3i** [comment]
For people who interested with latest up-to-date but non-official deb/rpm for Ubuntu/Debian/CentOS/RHEL/Fedora/openSUSE, I have a OBS repo for try: https://build.opensuse.org/project/show/home:alvistack

**Comment by afbjorklund** [comment]
We are having big stability problems with OBS when it comes to installing cri-o, would be nice with something a bit more stable (and official!) for a tool that is now required by the default installer. Especially if multiple versions

**Comment by hswong3i** [comment]
> We are having big stability problems with OBS when it comes to installing cri-o, would be nice with something a bit more stable (and official!) for a tool that is now _required_ by the default installer. Especially if multiple versions*

![8322C267-A56D-4266-99B1-45364678ADA3](https://user-images.githubusercontent.com/780562/149340143-41955e32-f536-4e01-938e-4fbb8af2db4c.png)

Hopefully this is what you are looking for :-)

**Comment by afbjorklund** [comment]
> Hopefully this is what you are looking for :-)

Putting the version in the name ? Wow, that's wild.

**Comment by afbjorklund** [comment]
Here are the current requirements:

Package: kubeadm
Version: 1.23.1-00
Priority: optional
Section: misc
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Installed-Size: 45.2 MB
Depends: kubelet (>= 1.19.0), kubectl (>= 1.19.0), **kubernetes-cni (>= 0.8.7), cri-tools (>= 1.19.0)**
Homepage: https://kubernetes.io
Download-Size: 8579 kB
APT-Manual-Installed: yes
APT-Sources: https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
Description: Kubernetes Cluster Bootstrapping Tool
 The Kubernetes command line tool for bootstrapping a Kubernetes cluster.

N: There are 233 additional records. Please use the '-a' switch to see them.

When using standard Ubuntu 20.04 LTS.

**Comment by feiskyer** [comment]
> @feiskyer @mrunalp do we wanna switch to CRI v1 before releasing 1.23? This would be a breaking change.

I think it's ok to cut the release without v1. It would need some time for runtimes to support and migrate to v1.

> Or do we wanna support both CRI versions in parallel? We could make it configurable, but it would increase the implementation effort.

Could we do this in the next release (e.g. 1.24)? In this way, crictl version won't need to be coupled with kubernetes and runtime versions.

**Comment by saschagrunert** [comment]
@feiskyer sounds good to me. :+1:

**Comment by saschagrunert** [comment]
Release build is in progress: https://github.com/kubernetes-sigs/cri-tools/runs/4841568433

**Comment by saschagrunert** [comment]
Done https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.23.0
