### ISSUE TITLE
The default docker CRI socket changed, in Kubernetes 1.24 and beyond

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes-sigs/cri-tools#868]
#### What happened:

WARN[0000] runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock]. As the default settings are now deprecated, you should set the endpoint instead. 

#### What you expected to happen:

WARN[0000] runtime connect using default endpoints: [unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead. 

#### How to reproduce it (as minimally and precisely as possible):

`sudo crictl`

#### Environment:

- Container runtime or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04 LTS
- Kernel (e.g. `uname -a`): 5.4.0
- Others:

----

https://github.com/kubernetes/kubernetes/issues/106917#issuecomment-1007238806

https://github.com/Mirantis/cri-dockerd

**Comment by iamhritik** [comment]
you have to update the crictl config like this:

`crictl config --set runtime-endpoint=unix:///run/containerd/containerd.sock`

**Comment by babu97** [comment]
replace the file located in   /etc/containerd/config.toml  with this 
```
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true
```
restart containerd after replacing the file 
```
sudo systemctl restart containerd
```
let me know if this fixed your issue

**Comment by afbjorklund** [comment]
Fixing containerd configuration is unrelated to this issue, which was about replacing dockershim with cri-dockerd...

It was completed years ago, so there is no need to comment further on this (closed) issue. User should set crictl.yaml

**Comment by kalelegs** [comment]
@iamhritik : you rock my friend!
