### ISSUE TITLE
[1.24] Remove dockershim from crictl code and docs

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes-sigs/cri-tools#870]
`crictl` currently defaults to `dockershim.sock`. We should update the default in advance of 1.24. Additionally, remove mentions of dockershim from the repo:

https://github.com/kubernetes-sigs/cri-tools/search?q=dockershim.sock

**Comment by afbjorklund** [comment]
Currently `crictl` supports multiple versions of kubernetes. Changing this would mean that it needs to be split.

i.e. the currrent 1.19 version installed supports any version 1.20 and up - including both 1.23 and 1.24

Note that there _is_ no default. There is just a list of locations to be searched, dockershim being one of them.

The user is supposed to pick a container runtime and configure it.

**Comment by afbjorklund** [comment]
@shannonxtreme 

The claim that dockershim is default seems to be from some old docs from Kubernetes 1.11

https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/

**Comment by afbjorklund** [comment]
Link to issue about fixing kubernetes.io documentation:
* https://github.com/kubernetes/website/issues/30976

**Comment by SergeyKanzhelev** [comment]
still a valid request. A few mentions of `dockershim.sock` has left in docs

**Comment by afbjorklund** [comment]
And code ?

**Comment by afbjorklund** [comment]
It would be nice to get this removal done for 1.30
