### ISSUE TITLE
crictl must work with containerd 1.5 - allow the fallback logic to CRI API v1alpha2

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes-sigs/cri-tools#883]
This is a follow up from https://github.com/kubernetes-sigs/cri-tools/pull/878#issuecomment-1022493135

Containerd 1.5 only implements CRI API `v1alpha2` and cri tools must support the same runtimes k8s supports. So there should be a fallback logic to `v1alpha2`.

**Comment by SergeyKanzhelev** [comment]
@saschagrunert what is the versioning story of CRI tools for CRI-O? How many versions back customers will expect to be supported?

**Comment by SergeyKanzhelev** [comment]
cc: @qiutongs

**Comment by saschagrunert** [comment]
> @saschagrunert what is the versioning story of CRI tools for CRI-O? How many versions back customers will expect to be supported?

Since CRI-O versionizes together with Kubernetes, we would have any issue with a breaking change here. We also support CRI v1 since a couple of releases (v1.21 I guess), so we're already good to go.

**Comment by saschagrunert** [comment]
One way to approach this would be to switch to the internal runtime and image services completely:

https://github.com/kubernetes-sigs/cri-tools/blob/8553b616d79b7753f4eda5fb9144cd8ca9eb9764/cmd/crictl/main.go#L135-L137

This service already features the conversion of the types, but it would mean that we bound the kubelet code tighter to crictl.

**Comment by afbjorklund** [comment]
Same problem with Docker (cri-dockerd), I guess it deserves a special issue.

```console
docker@minikube:~$ crictl --version
crictl version v1.21.0
docker@minikube:~$ crictl version
Version:  0.1.0
RuntimeName:  docker
RuntimeVersion:  20.10.12
RuntimeApiVersion:  1.41.0
docker@minikube:~$ cri-dockerd --version
cri-dockerd 0.2.0 (a4d1895)
docker@minikube:~$ crictl info
{
  "status": {
    "conditions": [
      {
        "type": "RuntimeReady",
        "status": true,
        "reason": "",
        "message": ""
      },
      {
        "type": "NetworkReady",
        "status": true,
        "reason": "",
        "message": ""
      }
    ]
  }
}
```

When upgrading cri-tools to latest/greatest (i.e. 1.24 pre-release), it no longer works:

```console
docker@minikube:~$ ./crictl-1.23.0 --version
crictl version v1.23.0
docker@minikube:~$ ./crictl-1.23.0 info
{
  "status": {
    "conditions": [
      {
        "type": "RuntimeReady",
        "status": true,
        "reason": "",
        "message": ""
      },
      {
        "type": "NetworkReady",
        "status": true,
        "reason": "",
        "message": ""
      }
    ]
  }
}
docker@minikube:~$ ./crictl --version
crictl version 1.23.0-18-g0871ebbc
docker@minikube:~$ ./crictl info
FATA[0000] getting status of runtime: rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService 
```

**Comment by afbjorklund** [comment]
> Since CRI-O versionizes together with Kubernetes, we would have any issue with a breaking change here. We also support CRI v1 since a couple of releases (v1.21 I guess), so we're already good to go.

I guess you mean "we would **not** have any" ? Normally CRI-O lags the Kubernetes releases for some time, but if it has already been implemented in a release version then I suppose you could* use cri-o `v1.23.1` with kubernetes `v1.24.0` ?

\* I think we are currently using crio 1.22.1 with k8s 1.23.3.

**Comment by saschagrunert** [comment]
> I guess you mean "we would **not** have any" ?

Yes, sorry for the confusion.

**Comment by afbjorklund** [comment]
Docker now installs containerd 1.5, fwiw

**Comment by saschagrunert** [comment]
Fixed with https://github.com/kubernetes-sigs/cri-tools/pull/889
