### ISSUE TITLE
Retrieve namespace/pod/container from a host PID

### ISSUE THREAD

**Issue by fjammes** [kubernetes-sigs/cri-tools#887]
#### What would you like to be added:

A feature to retrieve the namespace/pod/container/container primary pid from a pid retrieved on  host

#### Why is this needed:

If a process is misbehaving on the host, it might be helpful to quickly understand in which pod it is running.

**Comment by saschagrunert** [comment]
Hey @fjammes, thank you for the feature request! 

Can you elaborate a bit which kind of information would you expect to get and how a possible command invocation would look like?

What we can do is correlating the container PID (part of the optional `info` field of `crictl inspect`) to a container ID, but which output would you expect?
