### ISSUE TITLE
Running 'crictl images' does not return a comprehensive list of images

### ISSUE THREAD

**Issue by ejsealms** [kubernetes-sigs/cri-tools#891]
#### What happened: The service that I work on has a script that deletes images that are not being used because over time, these images become stale and they introduce security vulnerabilities. The script uses crictl to find all images on the machines. Over time, all of our machines started to report that they had many vulnerable images still on them. 

I went into the machines and ran 'crictl images' with some options and found that crictl was not aware of the existence of these images. To be sure, I ran 'crictl inspecti "sha256:xxx..."' using the hash of the images that were reported to be on the machine, but crictl said that it could not find the images. 

Next, I tried to find the images using the containerd CLI, specifically using the 'ctr --namespace=k8s.io images ls' command. This showed me way more images than the crictl command did, including those that were reported as vulnerable. Unfortunately, the containerd CLI is less capable than crictl in that it can't describe the images in as much detail, but the fact that it can find more images means that I need to use it if I want to have a secure application. 

TL;DR: Crictl is unable to find some images, containerd is able to find those same images. 

#### Environment:

- Container runtime or hardware configuration: Container runtime = containerd://1.4.9+azure
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="[https://www.ubuntu.com/"](https://www.ubuntu.com/%22)
SUPPORT_URL="[https://help.ubuntu.com/"](https://help.ubuntu.com/%22)
BUG_REPORT_URL="[https://bugs.launchpad.net/ubuntu/"](https://bugs.launchpad.net/ubuntu/%22)
PRIVACY_POLICY_URL="[https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"](https://www.ubuntu.com/legal/terms-and-policies/privacy-policy%22)
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
Linux aks-agentpool-################ 5.4.0-1068-azure #71~18.04.1-Ubuntu SMP Thu Jan 20 08:21:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by saschagrunert** [comment]
@mikebrow do you have any idea why this should happen?

**Comment by cyxinda** [comment]
I 

> #### What happened: The service that I work on has a script that deletes images that are not being used because over time, these images become stale and they introduce security vulnerabilities. The script uses crictl to find all images on the machines. Over time, all of our machines started to report that they had many vulnerable images still on them.
> I went into the machines and ran 'crictl images' with some options and found that crictl was not aware of the existence of these images. To be sure, I ran 'crictl inspecti "sha256:xxx..."' using the hash of the images that were reported to be on the machine, but crictl said that it could not find the images.
> 
> Next, I tried to find the images using the containerd CLI, specifically using the 'ctr --namespace=k8s.io images ls' command. This showed me way more images than the crictl command did, including those that were reported as vulnerable. Unfortunately, the containerd CLI is less capable than crictl in that it can't describe the images in as much detail, but the fact that it can find more images means that I need to use it if I want to have a secure application.
> 
> TL;DR: Crictl is unable to find some images, containerd is able to find those same images.
> 
> #### What you expected to happen: I expected crictl to find all of the images on the machine.
> #### How to reproduce it (as minimally and precisely as possible): It is largely a mystery to me why some images were not visible to crictl. One thing I noticed is that crictl was not able to find any images that had a prefix before the hash. For example, it would find something in the form "sha256:xxxx....", but not something in the form "myacr/containerrepository/component/sha256:xxxx..."
> #### Anything else we need to know?: I will have gotten rid of these images within the next week or so. If you want me to reproduce this issue, we need to move quickly.
> #### Environment:
> * Container runtime or hardware configuration: Container runtime = containerd://1.4.9+azure
>   NAME="Ubuntu"
>   VERSION="18.04.6 LTS (Bionic Beaver)"
>   ID=ubuntu
>   ID_LIKE=debian
>   PRETTY_NAME="Ubuntu 18.04.6 LTS"
>   VERSION_ID="18.04"
>   HOME_URL="[https://www.ubuntu.com/"](https://www.ubuntu.com/%22)
>   SUPPORT_URL="[https://help.ubuntu.com/"](https://help.ubuntu.com/%22)
>   BUG_REPORT_URL="[https://bugs.launchpad.net/ubuntu/"](https://bugs.launchpad.net/ubuntu/%22)
>   PRIVACY_POLICY_URL="[https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"](https://www.ubuntu.com/legal/terms-and-policies/privacy-policy%22)
>   VERSION_CODENAME=bionic
>   UBUNTU_CODENAME=bionic
>   Linux aks-agentpool-################ 5.4.0-1068-azure [Add portforward test #71](https://github.com/kubernetes-sigs/cri-tools/pull/71)~18.04.1-Ubuntu SMP Thu Jan 20 08:21:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

I have the same problem  that crictl was not able to find any images that had a prefix before the hash.
And don't know how to solve it .

**Comment by ejsealms** [comment]
@cyxinda I resolved this by using containerd instead of crictl. The command `ctr namespaces ls` will show all your containerd namespaces, and then you can run `ctr images ls --namespace=<your namespace>` to see all the images in that namespace. Then, to delete the images, you can run `ctr images rm --namespace=<your namespace> <your image>`

**Comment by cyxinda** [comment]
> @cyxinda I resolved this by using containerd instead of crictl. The command `ctr namespaces ls` will show all your containerd namespaces, and then you can run `ctr images ls --namespace=<your namespace>` to see all the images in that namespace. Then, to delete the images, you can run `ctr images rm --namespace=<your namespace> <your image>`

yes,it is true ctr can pull the images  .
But crictl can't find image with subffix of degist that is pulled by ctr in the namespace of k8s.io .
when the network is disconnected, if k8s cannot pull a  image with subffix, ctr cannot import the image.
