### ISSUE TITLE
Suggestion: Remove the fallback endpoints in a versioned release of crictl

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes-sigs/cri-tools#893]
The "default" runtime endpoints for `crictl` have been deprecated for more than three Kubernetes releases. We should consider removing the endpoints from crictl in a way that doesn't break functionality for users who rely on the fallback behaviour. 

Here's what I think should happen:

**After Kubernetes 1.24**:

* Remove the fallback endpoints from crictl
* Tie the change to a new version of cri-tools that coordinates with Kubernetes 1.25 (or whatever version this change makes it in time for)
* Update the [version matrix](https://github.com/kubernetes-sigs/cri-tools) for cri-tools.
* When running crictl v1.25+ without a runtime endpoint set, display an actionable error message (possibly with a link to the crictl docs for setting the endpoint).

I'm happy to chip in on work on this if accepted :)

![tumblr_mkl2hgtQo01s2b2mgo6_250](https://user-images.githubusercontent.com/30392854/153650685-f17aa04f-2ca3-4009-a622-89c36a9b950f.gif)

**Comment by SergeyKanzhelev** [comment]
this change of behavior will work for vendors who preinstall `crictl` and for manual installations, but may break automatic scripts that may stop working if they don't specify the endpoint. I'm not sure if there is any harm for having defaults, except the performance penalty for the end user. I wonder if we should un-deprecate it.

**Comment by shannonxtreme** [comment]
That's also an option. My concern comes from us having notes and warnings saying that the endpoints are deprecated. Wouldn't an automatic script continue to work if we gated the change behind a new version of cri-tools?

**Comment by afbjorklund** [comment]
The kubernetes installation should require installing and configuring `crictl`, currently it mentions it briefly in passing.

There is already a hard crash in kubeadm if `crictl` is missing, it might as well check if `/etc/crictl.yaml` is set up too ?

On a side note, it would be nice if it was more obvious to packagers that they _should_ split the "cri-tools" into two.

I don't think anyone cares about `critest`, but they do have care about `crictl` (with the removal of the dockershim)

**Comment by afbjorklund** [comment]
There are some bizarre failures, where crictl fails to detect a socket and falls back to docker (or containerd, or whatever)

So the guessing is just that: guessing. Most likely it would be better for everyone, if the configuration was explicit always.

**Comment by afbjorklund** [comment]
Note: the old packages for containerd, as well as the packages for cri-o, include the cri-tools configuration:

/etc/crictl.yaml
/etc/cni/net.d/10-containerd-net.conflist

/etc/crictl.yaml
/etc/cni/net.d/100-crio-bridge.conf
/etc/cni/net.d/200-loopback.conf

If the user installs the binaries themselves, they have to add the configuration (and systemd units) as well.

**Comment by afbjorklund** [comment]
The fallback endpoints seem to never be tried, possibly after the version bump from alpha to v1 with crictl 1.24

**Comment by SergeyKanzhelev** [comment]
I think it will be very hard to deprecate this behavior any time soon. I'd suggest we close this issue for now and re-open if decide to do it.

/close

**Comment by afbjorklund** [comment]
@SergeyKanzhelev if you require that it is set up for `kubeadm` in a future release, instead of using `-r` parameters like today, then you don't need this kind of workarounds/shims ?

It already checks for the program, so it could also verify the configuration. It is only "new" for the docker users, the other runtimes have already configured a socket for a _long_ time ?

**Comment by SergeyKanzhelev** [comment]
I realize it is configured in many cases. I just think that breaking even a few customers is unnecessary. This fallback logic is not too complicated to maintain. Even this page still suggests that fallback option exists: https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#general-usage

**Comment by afbjorklund** [comment]
Last time I tried it, the fallback option was broken anyway. So the recommendation is _still_ to configure, before using `crictl`.

It tries the containerd socket (without cri plugin enabled), before trying the cri-docker socket.

```
$ sudo crictl version
WARN[0000] runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead. 
ERRO[0000] unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/dockershim.sock: connect: no such file or directory" 
E0927 18:00:15.487934    7338 remote_runtime.go:189] "Version from runtime service failed" err="rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
FATA[0000] getting the runtime version: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService 
```

It worked OK for dockershim, but fails for cri-dockerd after it was moved to the end of the fallbacks.
