### ISSUE TITLE
deb/rpm builds haven't been updated for 8-10 months. Latest 1.21

### ISSUE THREAD

**Issue by Jeansen** [kubernetes-sigs/cri-tools#896]
https://github.com/kubernetes-sigs/cri-tools#debrpm-packages references deb/rpm builds. Latest Version is 1.21. 
See https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/cri-tools and also The same is true for https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/ .

Are they no longer maintained?

**Comment by saschagrunert** [comment]
Yeah the OBS packages are outdated, we should update them as soon as possible. Beside that, we should also update the version in the official Kubernetes packages. Ref: https://github.com/kubernetes/release/pull/2457

**Comment by saschagrunert** [comment]
Submitted a request for OBS: https://build.opensuse.org/request/show/959837

**Comment by afbjorklund** [comment]
The kubernetes package has now been updated, for the 1.23.5 release:

```
cri-tools/kubernetes-xenial,now 1.23.0-00 amd64 [installed]
```

**Comment by Jeansen** [comment]
Oh, great!
Works fine on my end. Should I close thins one then?

**Comment by saschagrunert** [comment]
Sure, I updated it in https://github.com/kubernetes/release/pull/2457
