### ISSUE TITLE
private registry tls self signed certificates

### ISSUE THREAD

**Issue by ydahan** [kubernetes-sigs/cri-tools#897]
I didn't find any working option to do one of the following:
1. add self signed certificate to trust list.
2. skip certificate verification

One cannot use private registry with or without certificate, didn't find any option to fix this.

Tried to add insecure_registries to /etc/crio/crio.conf and didn't work

**Comment by ydahan** [comment]
Found the way to make this work

**Comment by vhp1360** [comment]
hello.
so, how did you solve it?
