### ISSUE TITLE
Allow registry auth credentials to be set from environment variable

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes-sigs/cri-tools#903]
#### What would you like to be added:
The ability to input the AUTH_STRING or credentials for `crictl pull` using an environment variable.

#### Why is this needed:
The ability to supply credentials when crictl is being called by another process programmatically.

**Comment by saschagrunert** [comment]
Hey @josh-ferrell this seems to be a good idea and should be straightforward to implement. Are you planning to work on this?
