### ISSUE TITLE
ginkgo version aligning

### ISSUE THREAD

**Issue by mikebrow** [kubernetes-sigs/cri-tools#925]
We, containerd, are having problems moving up to v1.24.0 and post v1.24.0 critest with both parallel on and a skip and/or focus applied.

History here: https://github.com/containerd/containerd/pull/6894

Noting also that k/k is on a different version of ginkgo and ginkgo has the requirement of the installed version matching the library. This may cause some versioning issues when doing both critest and e2e buckets.  Let's discuss.

Cheers, Mike

**Comment by saschagrunert** [comment]
> We, containerd, are having problems moving up to v1.24.0 and post v1.24.0 critest with both parallel on and a skip and/or focus applied.

Is this something which has to be fixed in ginkgo?

> Noting also that k/k is on a different version of ginkgo and ginkgo has the requirement of the installed version matching the library. This may cause some versioning issues when doing both critest and e2e buckets. Let's discuss.

There are also efforts of moving k/k to ginkgo v2: https://github.com/kubernetes/kubernetes/pull/109111

**Comment by mikebrow** [comment]
missed this question @saschagrunert .. fu wei was taking a look, see pr ^

**Comment by saschagrunert** [comment]
@mikebrow if #930 got merged, would you need a new release of cri-tools?
