### ISSUE TITLE
Backward compatibility issues with v1.21.x kubernetes cluster

### ISSUE THREAD

**Issue by hasan4791** [kubernetes-sigs/cri-tools#928]
#### What happened:
With cri-tools v1.24.0, the images aren't getting pulled in the kubernetes 1.21 version. Does it support backward compatibility?
Also with 1.22.x & 1.23.x clusters, there are no issues.

#### What you expected to happen:
No issues should occur during image pull

#### How to reproduce it (as minimally and precisely as possible):
Run "crictl pull hello-world" in 1.21 kubernetes cluster

#### Anything else we need to know?:
Before v1.24 release, we were using cri-tools v1.23 that worked fine with 1.21.x clusters.
If its really a backward compatible issues, shall we get all version from opensuse repo as it always provides only the most recent release.
https://provo-mirror.opensuse.org/repositories/devel%3A/kubic%3A/libcontainers%3A/stable/CentOS_8_Stream/x86_64/

#### Environment:

- Container runtime or hardware configuration: crio-1.21
- OS (e.g: `cat /etc/os-release`): RHEL8
- Kernel (e.g. `uname -a`): 4.18.0-348.20.1.el8_5.x86_64
- Others:
```
[root@kube-bootstrap-iks-1652166943311262890 bootstrap]# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12+IKS", GitCommit:"8e414e117f0710d5de97d4ba4945c700b8cf224e", GitTreeState:"clean", BuildDate:"2022-04-20T19:09:30Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12+IKS", GitCommit:"8e414e117f0710d5de97d4ba4945c700b8cf224e", GitTreeState:"clean", BuildDate:"2022-04-20T19:07:09Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
[root@kube-bootstrap-iks-1652166943311262890 bootstrap]# 
[root@kube-bootstrap-iks-1652166943311262890 bootstrap]# crictl --version
crictl version 1.24.0
[root@kube-bootstrap-iks-1652166943311262890 bootstrap]# crictl pull hello-world
E0510 03:35:03.764625   11193 remote_image.go:238] "PullImage from image service failed" err="rpc error: code = Unavailable desc = error reading from server: EOF" image="hello-world"
FATA[0001] pulling image: rpc error: code = Unavailable desc = error reading from server: EOF 
[root@kube-bootstrap-iks-1652166943311262890 bootstrap]# 

```

**Comment by shinebayar-g** [comment]
It looks like crictl minor version should match kubernetes minor version as quoted here. https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#installing-crictl

> Download the version that corresponds to your version of Kubernetes.

**Comment by afbjorklund** [comment]
That would mean that it _can't_ be installed with the system, like the container runtime can.

**Comment by hasan4791** [comment]
Thank you all, looks like the crio rpms in opensuse upstream repo was having issues. We moved to the RH provided rpms & everything is fine btw.
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/

Also regarding the cri-tools rpms, it would be great if kubernetes version specific rpms also provided here.
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/x86_64/
