### ISSUE TITLE
Support darwin/arm64 architecture

### ISSUE THREAD

**Issue by unmarshall** [kubernetes-sigs/cri-tools#929]
#### What would you like to be added:
In https://github.com/kubernetes-sigs/cri-tools/releases there is no release for darwin/arm64 architecture.  Is there any plans to support this architecture? 

#### Why is this needed:
All new macbook's now come with M1 chipset which has this architecture.

**Comment by saschagrunert** [comment]
@unmarshall sure, do you wanna create a PR to contribute the change? :)

**Comment by wang-mask** [comment]
yet not
