### ISSUE TITLE
Only report error message if no runtime available

### ISSUE THREAD

**Issue by k82cn** [kubernetes-sigs/cri-tools#943]
#### What happened:

```
vagrant@bootstrap:~$ sudo crictl images list
WARN[0000] image connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/
crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead.
ERRO[0000] unable to determine image API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dia
ling dial unix /var/run/dockershim.sock: connect: no such file or directory"
IMAGE                      TAG                 IMAGE ID            SIZE
docker.io/library/ubuntu   16.04               b6f5076524258       46.5MB
docker.io/library/ubuntu   18.04               ad080923604aa       26.7MB

```

#### What you expected to happen:

Only report error message if no runtime available.

#### How to reproduce it (as minimally and precisely as possible):

crictl with containerd

#### Environment:

- Container runtime or hardware configuration: containerd
- OS (e.g: `cat /etc/os-release`): 

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial
```

- Kernel (e.g. `uname -a`): `Linux bootstrap 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Others:

**Comment by saschagrunert** [comment]
@k82cn thank you for reporting the issue, are you planning to work on a fix for it?

**Comment by k82cn** [comment]
> @k82cn thank you for reporting the issue, are you planning to work on a fix for it?

I'm ok with that :)

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes-sigs/cri-tools/issues/893
