### ISSUE TITLE
How to transfer from "docker run" to "crictl run"

### ISSUE THREAD

**Issue by lidh15** [kubernetes-sigs/cri-tools#951]
Previously I have a container started with something like "docker run --rm -it --shm-size 32G -privileged --cap-add IPC_LOCK -p 8000:80 -v /home/myhome:/workspace -d myimages /usr/sbin/init"
you see I have used following arguments:
--rm
-it
--shm-size
--privileged
--cap-add
-p
-v
-d
And now it seems that I need to run "crictl run container-config.json pod-config.json"
But I don't know how I should put these arguments into the config.json s, and the example (which is really old) seems to be too simple to place them.
Would you please offer an example supporting these arguments?

**Comment by lidh15** [comment]
ok close it

**Comment by saschagrunert** [comment]
Hey @lidh15, sorry for the late reply. Unfortunately this is not in scope of this project and we will not aim for CLI compatibility. We have a bunch of example in our CRI-O testdata: https://github.com/cri-o/cri-o/tree/main/test/testdata

The JSON format mainly maps to the CRI API: https://github.com/kubernetes/cri-api/blob/3af67d6e7a5160e066444dac2a62e6218d67066b/pkg/apis/runtime/v1/api.proto#L40-L65
