### ISSUE TITLE
Document statsp command for crictl.

### ISSUE THREAD

**Issue by kenneth-dsouza** [kubernetes-sigs/cri-tools#953]
Currently statsp command is not documented in cricitl.md, add the same to man page.
`$ git diff
diff --git a/docs/crictl.md b/docs/crictl.md
index c9045086..e2ea55ba 100644
--- a/docs/crictl.md
+++ b/docs/crictl.md
@@ -60,6 +60,7 @@ COMMANDS:
 - `update`:             Update one or more running containers
 - `config`:             Get and set crictl client configuration options
 - `stats`:              List container(s) resource usage statistics
+- 'statsp`:             List pod(s) resource usage statistics
 - `completion`:         Output bash shell completion code
 - `help, h`:            Shows a list of commands or help for one command
`

**Comment by saschagrunert** [comment]
@kenneth-dsouza thank you for reaching out! Yeah feel free to propose a PR containing the necessary changes. :pray:
