### ISSUE TITLE
critest for containerd `main` fails

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/cri-tools#960]
The test `main / ubuntu-18.04 / io.containerd.runc.v2 / crun` consistently fails over all PRs:

https://github.com/kubernetes-sigs/cri-tools/runs/7463687194
https://github.com/kubernetes-sigs/cri-tools/runs/7443618160
https://github.com/kubernetes-sigs/cri-tools/runs/7445694734

@mikebrow did we change anything in the containerd configuration which makes the tests fail?

**Comment by mikebrow** [comment]
might be fixed now https://github.com/containerd/containerd/pull/7198
