### ISSUE TITLE
Using `crictl rmi` doesn't actually remove anything

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes-sigs/cri-tools#964]
#### What happened:

Removing images with cri-tools doesn't seem to be working ?

#### What you expected to happen:

The image should be removed, or at least an error reported ?

Says `Deleted: `

#### How to reproduce it (as minimally and precisely as possible):

`sudo crictl rmi`

#### Anything else we need to know?:

Workaround:

`docker rmi`

#### Environment:

- Container runtime or hardware configuration: Docker 20.10.17
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.4 LTS
- Kernel (e.g. `uname -a`): 5.4.0-122-generic
- Others: Kubernetes v1.24.3, crictl v1.21.0

**Comment by afbjorklund** [comment]
Seems to be known:
* #568

**Comment by afbjorklund** [comment]
It was a problem with the documentation, the command only expects full Id (sha256: etc)
When it gets a proper Id as input, then it actually removes all the tags referencing it.

Apparently trying to remove an image that does not exist, or an invalid Id is **not** an error.
This is not only the docker implementation, it is handled the same way in containerd:

```go
                if err == store.ErrNotExist {
                        // return empty without error when image not found.
                        return &runtime.RemoveImageResponse{}, nil
                }
```

**Comment by pmengelbert** [comment]
Related to this, an image with no associated `repoTags` cannot be removed by imageID:

```bash
# crictl images -o json | jq '.images[] |select(.repoTags == [])'
{
  "id": "sha256:0ebe7501b7b5ada018c460eb2519066b7c897c71214fff4aea4550513c04bfd8",
  "repoTags": [],
  "repoDigests": [
    "docker.io/library/import-2022-11-16@sha256:ffd9f8a307fab422201b95fd1de54e21a7a71de465c35ab4203f02480cc816cd"
  ],
  "size": "2109278",
  "uid": null,
  "username": "",
  "spec": null
}

# crictl rmi sha256:0ebe7501b7b5ada018c460eb2519066b7c897c71214fff4aea4550513c04bfd8
# echo $?
0
# crictl images -o json | jq '.images[] | select(.id == "sha256:0ebe7501b7b5ada018c460eb2519066b7c897c71214fff4aea4550513c04bfd8")'
{
  "id": "sha256:0ebe7501b7b5ada018c460eb2519066b7c897c71214fff4aea4550513c04bfd8",
  "repoTags": [],
  "repoDigests": [
    "docker.io/library/import-2022-11-16@sha256:ffd9f8a307fab422201b95fd1de54e21a7a71de465c35ab4203f02480cc816cd"
  ],
  "size": "2109278",
  "uid": null,
  "username": "",
  "spec": null
}
```

**Comment by afbjorklund** [comment]
Seeing the same thing:

`Inspected image ID sha256:36633b450fe349591edbd9952536b253f17a352cb0663541640ca45173626869 does not match image sha256:36633b450fe349591edbd9952536b253f17a352cb0663541640ca45173626869`

**Comment by afbjorklund** [comment]
@pmengelbert I cannot reproduce, as long as you give the full id then it removes fine.

At least with cri-dockerd, so maybe something that is specific to containerd or crio ?

**Comment by thibaut-lo** [comment]
@afbjorklund I do face a similar issue

<img width="897" alt="image" src="https://user-images.githubusercontent.com/66995824/233648763-c9f54626-e009-4d23-8cfa-e4417110b2e3.png">

**Comment by SergeyKanzhelev** [comment]
@thibaut-lo please use --debug output as suggested and also what runtime/versions do you use?
