### ISSUE TITLE
crictl version seems incorrect

### ISSUE THREAD

**Issue by rgl** [kubernetes-sigs/cri-tools#971]
#### What happened:

After installing 1.25.0 (from https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.25.0/crictl-v1.25.0-linux-amd64.tar.gz), it seems the reported version is incorrect:

```console
$ sudo crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.6.8
RuntimeApiVersion:  v1
```

#### What you expected to happen:

Version reported as 1.25.0.

**Comment by saschagrunert** [comment]
@rgl thank you for this request. The version returned by `crictl version` is the version the runtime reports via the CRI:
https://github.com/kubernetes/cri-api/blob/37ca8f0f0b492517b114daa87ab0406ae1e20a74/pkg/apis/runtime/v1/api.proto#L150-L161

So it's totally up to containerd which version they report in that request.

**Comment by rgl** [comment]
Ah, so its the version of the server implementation. Maybe it can also report its own version?

For example, as `runc` does:

```console
$ runc --version
runc version 1.1.4
commit: v1.1.4-0-g5fd4c4d1
spec: 1.0.2-dev
go: go1.17.10
libseccomp: 2.5.4
```

**Comment by saschagrunert** [comment]
It should via `crictl --version`

**Comment by rgl** [comment]
Oh, that was silly on my part... Sorry! I've mistaken the two.
