### ISSUE TITLE
`crictl rmi --prune` shows no output for untagged images removed

### ISSUE THREAD

**Issue by thomasf7** [kubernetes-sigs/cri-tools#976]
#### What happened:

Running `crictl rmi --prune` does not log information about all the images pruned as it only prints those that are tagged and images that are referenced by digest are pruned, but this is not reflected in the logs.

This looks to be because the [loop to print this info](https://github.com/kubernetes-sigs/cri-tools/blob/85c21d32b32681271bac1e8602dab9725b32f89f/cmd/crictl/image.go#L409-L411) is over the repoTags:

```go
for _, repoTag := range status.Image.RepoTags {
	fmt.Printf("Deleted: %s\n", repoTag)
}
```

But for images pulled by digest, RepoTags is nil.

#### What you expected to happen:

If the digest is known, it would be great to have this print `Deleted: <repo>@<digest>\n`, but if that is not possible there should at least be some output that an image was deleted e.g. `Deleted: untagged <imagename> with id <imageid>\n`

#### How to reproduce it (as minimally and precisely as possible):

1. Reference image by digest
2. Remove container referencing image
3. Run `crictl rmi --prune`
4. See no output related to above image.

**Comment by saschagrunert** [comment]
@thomasf7 yeah this makes sense to me. Do you consider working on this?

**Comment by thomasf7** [comment]
@saschagrunert sure I can take a crack at it
