### ISSUE TITLE
Add default endpoints

### ISSUE THREAD

**Issue by lengrongfu** [kubernetes-sigs/cri-tools#981]
#### What would you like to be added:

Add `unix:///var/run/containerd/containerd.sock` to default endpoints.

#### Why is this needed:

Current i running containerd in the macos, serving address is `/var/run/containerd/containerd.sock`, but i use crictl pull image, find this endpoint is not in default endpoints.

- containerd start log
```shell
time="2022-09-03T11:50:33.353307000+08:00" level=info msg=serving... address=/var/run/containerd/containerd.sock
time="2022-09-03T11:50:33.353411000+08:00" level=info msg="containerd successfully booted in 0.236748s"
```
- crictl pull nginx
```shell
$ crictl pull nginx
WARN[0002] image connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead.
ERRO[0003] unable to determine image API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/dockershim.sock: connect: no such file or directory"
ERRO[0003] unable to determine image API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: no such file or directory"
ERRO[0003] unable to determine image API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /run/crio/crio.sock: connect: no such file or directory"
ERRO[0003] unable to determine image API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: no such file or directory"
FATA[0003] unable to determine image API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: no such file or directory"
```

**Comment by afbjorklund** [comment]
When using [systemd](https://github.com/containerd/containerd/blob/main/containerd.service), it uses `/run/containerd/containerd.sock`.

And then `/var/run` is set up as as just symbolic link to `/run`...

So it doesn't _need_ the legacy `/var` location, like docker did ?

`runtime-endpoint: unix:///run/containerd/containerd.sock`

**Comment by afbjorklund** [comment]
Note that all default endpoints are deprecated anyway:

* https://github.com/kubernetes-sigs/cri-tools/issues/893

**Comment by afbjorklund** [comment]
I missed your point about running containerd on **macos***

I didn't know that Mac nodes were supported, and don't know where the socket "should" be stored on that platform... If the issue is about better support for Darwin, then you can disregard my comments about systemd.
